### PR TITLE
[develop] Fix installation location of header file `eosio.version.hpp`

### PR DESCRIPTION
**Pull request by johndebord**
Fixes [#8280](https://github.com/EOSIO/eos/issues/8280). `eosio.version.hpp` now, by default, installs in directory `/usr/local/include/eosio/`, as opposed to `/usr/local/include/`.

### CODE REVIEW

**Comment by swatanabe-b1** [comment]
If you're renaming it, eosio/version.hpp would be better.  There's no reason to duplicate the eosio.

**Comment by heifner** [comment]
@johndebord can we move this forward?

**Comment by johndebord** [comment]
> @johndebord can we move this forward?

Yes, I believe we can. But I suppose I will take @swatanabe-b1's suggestion and rename the file to `version.hpp` as opposed to it being `eosio.version.hpp`. So I'll make those three commits on the three branches and run the tests to make sure everything still works.

**Comment by swatanabe-b1** [comment]
Also, `version.hpp` doesn't compile.

**Comment by jeffreyssmith2nd** [comment]
Rebased and force pushed to get the latest CI to run so we can merge.

**Pull request merged**
