### PR TITLE
add covert_to_type for name

### PR DESCRIPTION
**Pull request by allenhan2**
## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Consensus Changes
- [x] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

For issue: https://github.com/EOSIO/eos/issues/9195
Added test cases for all digits name.

### CODE REVIEW

**Comment by allenhan2** [comment]
This fix is not for review yet

**Comment by jeffreyssmith2nd** [comment]
If this PR is not ready for review, the recommended approach is to make it a draft PR. Since this PR has already been created, you can see an option to convert it to a draft on the sidebar.

Screen Shot 2020-07-10 at 08 23 17

**Comment by allenhan2** [comment]
> If this PR is not ready for review, the recommended approach is to make it a draft PR. Since this PR has already been created, you can see an option to convert it to a draft on the sidebar.
> 
> Screen Shot 2020-07-10 at 08 23 17

Thanks, convert to draft instead

**Review by b1bart — APPROVED** [review]

**Comment by b1bart** [comment]
Accidentally approved, @allenhan2 please review and close or comment on timeline to completion

**Pull request merged**
