### PR TITLE
updated scripts to support Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ndcgundlach**
## Change Description

Updated build script to support ubuntu 20.04.  Changes to cicd are not included as there have been changes made to pipeline to accommodate.

## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

closes #9292 thank you @pnx for your effort

### CODE REVIEW

**Comment by ndcgundlach** [comment]
> Please see minor differences in #9292 and address here if relevant or not

Only difference is whitespace.

**Comment by b1bart** [comment]
> > Please see minor differences in #9292 and address here if relevant or not
> 
> Only difference is whitespace.

https://github.com/EOSIO/eos/pull/9292/files#diff-4fd38311f6f2d1669525ae2456054947R243 ?

**Comment by spoonincode** [comment]
Is there a reason not to take #9292 instead?

**Comment by ndcgundlach** [comment]
> Is there a reason not to take #9292 instead?

Either will work.  Originally there were going to be other changes added, that is why this branch.  Those were obviated by changes that Zack made.

**Comment by nksanthosh** [comment]
Fixes #9006 on develop

**Pull request merged**
