### PR TITLE
test for existence of "data" field when printing action result, introduced by PR #10100

### PR DESCRIPTION
**Pull request by praphael**
fix cleos bug  where "data" field does not exist in action results, introduced by PR #10100 

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ x] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [x] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Review by heifner — CHANGES_REQUESTED** [review]
Can you add a test that would fail before and now work.

**Review by softprofe — CHANGES_REQUESTED** [review]
The change looks safe to me, it only add a check for act["data"], however, add test case(s) will make this PR perfect. Please test for both the act['data'] exist/not exist before merge.

**Comment by praphael** [comment]
Ok I added a test, in order to test run 
`ctest --output-on-failure -L cleos_test`
It should pass

To check against older branch, copy cleos executable into programs/cleos.  The test should now fail. You might want to make a backup of cleos executable here before you do this.

**Review by jgiszczak — APPROVED** [review]
Being a little less cavalier about our assumptions of what nodeos returns is an improvement we should embrace.

**Review by heifner — APPROVED** [review]

**Review by softprofe — APPROVED** [review]

**Pull request merged**
