### PR TITLE
vote function in the boot-sequence shell is duplicated

### PR DESCRIPTION
**Pull request by evsward**
There are two vote function and they are same, reduce one of them.

### CODE REVIEW

**Comment by evsward** [comment]
Sorry, but I think it's a useful step for testing          the performance of blockchain.

**Comment by evsward** [comment]
I have tested the shell modified and it worked well, it's very convenient.

**Comment by wanderingbort** [comment]
@tbfleming is in the right here.  we would gladly merge the duplicate removal and my create an alternate PR to do so but, in general committing unrelated changes to the branch makes it hard to accept a PR.  In the future you can avoid this by making your changes in branches (instead of directly in your fork of `master`) so that they may be independently accepted.

**Comment by evsward** [comment]
It's a pity but also thank you for your kindly remind. @wanderingbort

**Pull request closed without merging**
