### PR TITLE
Introduce get_transaction_merkle_proof RPC

### PR DESCRIPTION
**Pull request by conr2d**
## Change Description

Merkle proof is very basic feature used in inter-blockchain communication. It can be done in application level, but it would be helpful provided by RPC API.

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [x] API Changes

`/v1/chain/get_transaction_merkle_proof` is added.

## Documentation Additions
- [x] Documentation Additions

API needs to be documented.

### CODE REVIEW

**Comment by conr2d** [comment]
@swatanabe-b1 
Thank you for your review. Is there any conventional way to test RPC in this repository? I couldn't find any tests for other RPCs, so I'm not sure where to put my test in.

**Comment by swatanabe-b1** [comment]
It should probably go in tests/.  You can add a getProof method in tests/Node.py.

**Comment by swatanabe-b1** [comment]
This should really be handled in the SDKs instead as a new RPC endpoint.

**Comment by conr2d** [comment]
@swatanabe-b1 This proof can be acquired from the result of `/v1/chain/get_block` with full list of transactions, but I thought that getting whole block costs too much for getting a proof of one transaction. Can you let me know what SDK you mentioned means? (eosjs or history-tools?)

**Pull request closed without merging**
