### PR TITLE
add compile time option to enforce a chain id 📦

### PR DESCRIPTION
**Pull request by spoonincode**
## Change Description

SHIP clients often do not perform any validation of the blocks they are receiving. For high assurance deployments SHIP clients need complete confidence they are receiving fully validated blocks. #9721 added a compile time option to disable options in nodeos that disable full validation. With proper deployment permissions, #9963 can make it easier to prove that the SHIP client is connecting to the SHIP endpoint it expects (a fully validating trustworthy nodeos). Still, the SHIP client doesn't actually have proof that a fully validating nodeos is following the expected "real" chain (consider a malicious actor starting a fully trustworthy nodeos with a malicious genesis.json and then feeding that rouge chain with actions on accounts the SHIP client is looking for).

This adds a compile time option `-DEOSIO_REQUIRE_CHAIN_ID=` where nodeos will only operate with a given chain id. An additional tool is added, `eosio-chainid`, which will print the chain id of a given genesis json which may make it easier to determine the proper chain id before building. I'm not sure the additional tool is worth it over just starting nodeos with a genesis json and doing a `get info`?

I have no idea what to do about unit tests when this option is enabled.

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by spoonincode** [comment]
hmmm... actually, let me think this over a little more

**Comment by matthewdarwin** [comment]
@spoonincode having a way to get the chain_id from a genesis.json file would be very convenient when starting a new chain. Doesn't have to be a separate tool.. could be baked into nodeos itself  `nodeos --print-chain-id-from-genesis --genesis-json=filename`

**Comment by spoonincode** [comment]
The issue I have with baking these sort of things in to nodeos is that they aren't scriptable like I'd expect a unixy tool to be. Look at say `--print-build-info` or `--print-genesis-json` you can't just
```
BUILD_INFO=$(nodeos --print-build-info)
```
because 1) it goes out stderr, and 2) you get all sorts of other log trash when you run this command.

**Comment by spoonincode** [comment]
Opening back up since I thought about it more.

**Review by heifner — APPROVED** [review]

**Pull request merged**
