### PR TITLE
 Be proper UNIX citizens in expected directory hierarchy.

### PR DESCRIPTION
**Pull request by jgiszczak**
Support independent data and config directories in eosiod.
Start successfully on first launch whether installed or just built.
Honor EOSIO_ROOT environment variable in eosiod.
Regularize whitespace in eosiod main.cpp.
Remove cruft and fix typo in top level CMakeLists.txt.
Add support for CMake v3.6 packaging features, and emulate in older versions.
Update skeleton contract if it changes, and install it in an eosio directory.
Add an eosio user and group in .deb package and set appropriate permissions.
Regularize whitespace in various CMakeLists.txt.
Add libmongoc dependency to Debian package if built with mongo support.
Add self-registration to template plugin.
Remove last reference to steemd in CMakeLists.txt.

### CODE REVIEW

**Comment by jgiszczak** [comment]
The GNUInstallDirs module is no help at all for resolving /usr vs /usr/local prefixes.
${CMAKE_INSTALL_BINDIR} is simply the string literal 'bin'.  No magic.
No help.  ${CMAKE_INSTALL_FULL_BINDIR} is '/usr/local/bin' which is
the wrong path for a prebuilt binary.  /usr/local is still unsupportable
as long as CPack is defective by design.  (Or until Debian and
derivatives adopt the FreeBSD convention of putting absolutely
everything into /usr/local, including etc, and eradicating the
distinction between packaged and locally built binaries.)

**Comment by spoonincode** [comment]
> The GNUInstallDirs module is no help at all for resolving /usr vs /usr/local prefixes.
${CMAKE_INSTALL_BINDIR} is simply the string literal 'bin'. No magic.
No help. 
That sounds exactly what is expected. The "make install" path ends up being $DESTDIR/$CMAKE_INSTALL_PREFIX/$CMAKE_INSTALL_BINDIR

**Comment by jgiszczak** [comment]
Which would be fine if the only things we were installing were binaries.  We have more than that.  To deal with that, the "make install" path ends up being $DESTDIR/$CMAKE_INSTALL_PREFIX/usr/$CMAKE_INSTALL_BINDIR for binaries and $DESTDIR/$CMAKE_INSTALL_PREFIX/$CMAKE_INSTALL_SYSCONFDIR/eosio/node_00 for the config.ini and genesis files and $DESTDIR/$CMAKE_INSTALL_PREFIX/$CMAKE_INSTALL_LOCALSTATEDIR/log/eosio for eosiod output and $DESTDIR/$CMAKE_INSTALL_PREFIX/$CMAKE_INSTALL_LOCALSTATEDIR/lib/eosio for eosiod's block log and shared memory backing store.

**Comment by spoonincode** [comment]
That's not quite how it works, check the docs. /usr is treated specially
https://cmake.org/cmake/help/v3.10/module/GNUInstallDirs.html
So for CMAKE_INSTALL_PREFIX=/usr, 
CMAKE_INSTALL_BINDIR gets you,  /usr/bin
CMAKE_INSTALL_SYSCONFDIR,  /etc
CMAKE_INSTALL_LOCALSTATEDIR, /var

**Comment by jgiszczak** [comment]
The docs may imply that, but that's not actually what happens.

**Comment by spoonincode** [comment]
Works for me when using FULL dirs.

```
include(GNUInstallDirs)

install(FILES mybinfile DESTINATION ${CMAKE_INSTALL_FULL_BINDIR})
install(FILES myetcfile DESTINATION ${CMAKE_INSTALL_FULL_SYSCONFDIR}/eosio)
install(FILES myvarfile DESTINATION ${CMAKE_INSTALL_FULL_LOCALSTATEDIR}/eosio)
```

```
$ cd build
$ cmake ..
$ make DESTDIR=$PWD/install install
-- Installing: /home/spoon/cmaketest/build/install/usr/local/bin/mybinfile
-- Installing: /home/spoon/cmaketest/build/install/usr/local/etc/eosio/myetcfile
-- Installing: /home/spoon/cmaketest/build/install/usr/local/var/eosio/myvarfile
$ rm -Rf *
$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
$ make DESTDIR=$PWD/install install
-- Installing: /home/spoon/cmaketest/build/install/usr/bin/mybinfile
-- Installing: /home/spoon/cmaketest/build/install/etc/eosio/myetcfile
-- Installing: /home/spoon/cmaketest/build/install/var/eosio/myvarfile
```

**Comment by jgiszczak** [comment]
Now `make package` and install that.

**Comment by spoonincode** [comment]
```
$ cat ../CMakeLists.txt 
include(GNUInstallDirs)
set(CPACK_SET_DESTDIR "ON")
set(CPACK_GENERATOR "TGZ;DEB")
set(CPACK_PACKAGE_CONTACT "spoon@spoon.invalid")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
include(CPack)

install(FILES mybinfile DESTINATION ${CMAKE_INSTALL_FULL_BINDIR})
install(FILES myetcfile DESTINATION ${CMAKE_INSTALL_FULL_SYSCONFDIR}/eosio)
install(FILES myvarfile DESTINATION ${CMAKE_INSTALL_FULL_LOCALSTATEDIR}/eosio)
$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
$ make package
CPack: - package: /home/spoon/cmaketest/build/Project-0.1.1-Linux.tar.gz generated.
CPack: - package: /home/spoon/cmaketest/build/Project-0.1.1-Linux.deb generated.
$ tar tlf /home/spoon/cmaketest/build/Project-0.1.1-Linux.tar.gz
usr/
usr/bin/
usr/bin/mybinfile
etc/
etc/eosio/
etc/eosio/myetcfile
var/
var/eosio/
var/eosio/myvarfile
$ dpkg --contents /home/spoon/cmaketest/build/Project-0.1.1-Linux.deb
drwxr-xr-x root/root         0 2018-03-02 14:48 ./etc/
drwxr-xr-x root/root         0 2018-03-02 14:48 ./etc/eosio/
-rw-r--r-- root/root         0 2018-03-02 14:09 ./etc/eosio/myetcfile
drwxr-xr-x root/root         0 2018-03-02 14:48 ./usr/
drwxr-xr-x root/root         0 2018-03-02 14:48 ./usr/bin/
-rw-r--r-- root/root         0 2018-03-02 14:08 ./usr/bin/mybinfile
drwxr-xr-x root/root         0 2018-03-02 14:48 ./var/
drwxr-xr-x root/root         0 2018-03-02 14:48 ./var/eosio/
-rw-r--r-- root/root         0 2018-03-02 14:09 ./var/eosio/myvarfile
```
This is correct right?

**Comment by jgiszczak** [comment]
That is correct.

This:

> Each CMAKE_INSTALL_FULL_<dir> value contains an absolute path constructed from the corresponding destination by prepending (if necessary) the value of CMAKE_INSTALL_PREFIX.

does not convey this:

> $ cmake -DCMAKE_INSTALL_PREFIX=/usr ..

to my mind at all.  Once this merge is complete, the cmake scripts are yours.

**Comment by spoonincode** [comment]
I played around with this branch for a handful of minutes. My primary concern has been about preserving behavior for --
```
cmake -DCMAKE_INSTALL_PREFIX=/usr .....
make DESTDIR=${staging_dir} install
```
as that is behavior expected from most package managers. This branch works well with 2 exceptions:
1) I get a /usr/usr/{lib,include} for appbase and chainbase. IMO we should not be installing these -- installing eosio is not a delivery vehicle for appbase or chainbase. But this can be handled in a separate debate / PR.
2) I get a /usr/usr/share with the "eosio contractsdk libraries". This is my doing from a fix with a marked "#TODO: Fix this path on pending cmake install changes" so I can change this after merging.

**Comment by jgiszczak** [comment]
/etc/eosio, /var/log/eosio, and /var/lib/eosio are all set to ownership by the eosio user, and the eosiod binary is as well, and setuid.  Read the postinst script for details.  It's executed during installation of the Debian package, and works quite well.

**Comment by jgiszczak** [comment]
`appbase` installs to the correct location.  You got `/usr/usr` because you didn't `git submodule update` when you switched branches.  `chainbase` is no longer installed at all.  Its `CMakeLists.txt` no longer includes any `install` directives.

**Comment by spoonincode** [comment]
>appbase installs to the correct location. You got /usr/usr because you didn't git submodule update when you switched branches. chainbase is no longer installed at all. Its CMakeLists.txt no longer includes any install directives.

I double checked and was up to date. It seems like they still install given what's in the repo

https://github.com/EOSIO/chainbase/blob/master/CMakeLists.txt#L74
https://github.com/EOSIO/appbase/blob/master/CMakeLists.txt#L59

**Comment by jgiszczak** [comment]
Damnit.  I'm really getting tired of git submodules.  Fixed my remote urls so my commits and pushes now work.  Creating PRs for both.

**Pull request merged**
