### PR TITLE
MongoDB plugin filter based on action trace

### PR DESCRIPTION
**Pull request by chengevo**
This PR addresses issue #5292

### CODE REVIEW

**Comment by heifner** [comment]
Nice catch and write up.

**Comment by chengevo** [comment]
I'm not sure why it failed on first two builds, and apparently I have no access to the building logs, so is there anything I can do to fix these?

**Comment by heifner** [comment]
Assuming that is an issue with our build machine. Looking into it.

**Comment by heifner** [comment]
If you get a chance before me, would you mind rebasing to release/1.2.x. Would like to get this in the next patch release.

**Comment by chengevo** [comment]
Sure, will do

**Comment by heifner** [comment]
Rebased to release/1.2.x in #5306

**Pull request closed without merging**
