### PR TITLE
[in progress] sql_db_plugin

### PR DESCRIPTION
**Pull request by asiniscalchi**
plugin to communicate with :

DB2
Firebird
MySQL
ODBC with specific database driver
Oracle
PostgreSQL
SQLite 3

SQL databases using SOCI (https://github.com/SOCI/soci) lib

usage ex:

$ ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::sql_db_plugin --sql_db-uri="postgresql://dbname=eos"

or 

$ ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::sql_db_plugin --sql_db-uri="sqlite3://dbname=eos"

### CODE REVIEW

**Comment by gleehokie** [comment]
@asiniscalchi thanks for this contribution!  Do you want us to review the code now and merge it or wait until it is complete?

**Comment by bytemaster** [comment]
I'm very excited by this work, lets get conflicts resolved.

**Comment by asiniscalchi** [comment]
@gleehokie I resolved the conflicts. 
Don't mind if you already merge it in the repo.

**Comment by gleehokie** [comment]
@asiniscalchi builds are failing on all platforms except Ubuntu.  Click on the Details link in the list of checks, this will take you to Buildkite the CI system we are using.

**Comment by asiniscalchi** [comment]
@gleehokie I tried but I always get a Page Not Found...

**Comment by asiniscalchi** [comment]
screenshot from 2018-05-13 20-15-14

**Comment by gleehokie** [comment]
@asiniscalchi you should get a prompt to login, once you create an account you should have read-only access to Buildkite.  Please try again, if you still see the Page Not Found screen then reach out to me on Telegram and we can figure out the problem.

This is what I see when I access https://buildkite.com/EOSIO/eosio/builds/805 in an Incognito window on Chrome:

image

**Pull request merged**
