### PR TITLE
remove init() contract ABI call from setcode

### PR DESCRIPTION
**Pull request by bytemaster**
We no longer have the init() entry point for smart contracts, instead everything flows through apply().

We also no longer want to execute code within 30 seconds of an update to the code to give the node a chance to compile/cache the contract.

This update does not enforce the 30 second delay, but does remove the instant call to init() via inline notice of setcode.

### CODE REVIEW

**Comment by brianjohnson5972** [comment]
wasm_tests/memory_operators test is failing in travis.

@spoonincode should we change the wasm_tests.cpp memory_operators test to use current_memory and grow_memory in apply (instead of init), so that we are still verifying that they cannot be called?

../tests/wasm_tests/wasm_tests.cpp(510): error: in "wasm_tests/memory_operators": exception fc::unhandled_exception expected but not raised
../tests/wasm_tests/wasm_tests.cpp(513): error: in "wasm_tests/memory_operators": exception fc::unhandled_exception expected but not raised
*** 2 failures are detected in the test module "Master Test Suite"

**Comment by spoonincode** [comment]
Yes but there are a few other tests in wasm_tests that are going to require a little more advanced changes.

**Comment by brianjohnson5972** [comment]
How come they are not failing?

On Thu, Jan 25, 2018 at 10:28 AM, Matt Witherspoon <notifications@github.com

**Comment by spoonincode** [comment]
Looks like it's only the mutable global test. And it passes because it relied on init() trashing a variable. Without init() nothing trashes that variable.

**Pull request merged**
