### PR TITLE
fix build when build path has spaces - 1.8.x

### PR DESCRIPTION
**Pull request by skoyya-bo**
## Change Type
**Select ONE**
- [ ] Documentation

- [x] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by brianjohnson5972** [comment]
@skoyya-bo can you indicate if this is a clean cherry-pick of fix_build_space_path, or if you had to make changes, so we know how close we need to inspect this?

**Comment by brianjohnson5972** [comment]
Missing change for libraries/appbase/version.cmake.in (should have submodule change here and also change in that file in the appbase repo)

**Comment by skoyya-bo** [comment]
> @skoyya-bo can you indicate if this is a clean cherry-pick of fix_build_space_path, or if you had to make changes, so we know how close we need to inspect this?

Its same change but I didnt really do a cherry-pick. Did the changes manually.

**Comment by jeffreyssmith2nd** [comment]
Closing as this is not complete and not on the radar to have someone else take over.

**Pull request closed without merging**
