### PR TITLE
Hi, This documentation is for Chinese developer.

### PR DESCRIPTION
**Pull request by WildDylan**
1. Complete local testnet under master branch user guide.

Next chinese guide plan:

1. public testnet after tested dawn-3.x by myself
2. CLI, tools, keywords explain, chinese WIKI guide in other repo.
3. Chinese commented demo and files.

### CODE REVIEW

**Comment by bytemaster** [comment]
We should wait to translate this until README is finalized in english.

**Comment by WildDylan** [comment]
@bytemaster i don't think so. Now, many many developer learn how to dev on eos. When you complete many many developer works, it's late. 
traslate should day by day, english update, chinese will update.

**Comment by pokerchain** [comment]
When will have the final version readme ?

**Comment by bytemaster** [comment]
TUTORIAL.md is up to date and could be translated, not sure on status of README.md .

**Comment by gleehokie** [comment]
@WildDylan, thanks for your changes.  The README.md file is under heavy modification and will be much simpler after today since we are moving most content to the GitHub Wiki section for the eos repository.  I will let you know next week when that is stable and can be translated.

Thanks again!

**Comment by WildDylan** [comment]
@gleehokie will translate TUTORIAL.md and wait message for README.md here.

**Comment by gleehokie** [comment]
@WildDylan the TUTORIAL.md has been moved to the Wiki here (https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts).

The entire Wiki needs to be translated into multiple languages, but I do warn you that we are going to be modifying it heavily over the next few weeks, so you may want to hold off.  It's up to you.

Thanks for your help!

**Comment by WildDylan** [comment]
Chinese version for TUTORIAL.md (Getting-Started-With-Contracts). i can't pull request the wiki, so fork this repo and update wiki in my project。

[https://github.com/WildDylan/eos/wiki/Tutorial-Getting-Started-With-Contracts_zh.md](https://github.com/WildDylan/eos/wiki/Tutorial-Getting-Started-With-Contracts_zh.md)

**Comment by WildDylan** [comment]
@gleehokie @bytemaster

**Pull request closed without merging**
