### PR TITLE
SQL plugin

### PR DESCRIPTION
**Pull request by kesar**
Dump blockchain into SQL database

Fixes https://github.com/EOSIO/eos/issues/3450
Fixes https://github.com/EOSIO/eos/issues/3030

### CODE REVIEW

**Comment by chenfengqiannian** [comment]
Wow,I waited for a long time,thanks you.

**Comment by seedceo** [comment]
Will this plugin can handle 10.000 TPS?

**Comment by kesar** [comment]
> is it sql_plugin working well now? what kind of sql DBs are supported? Thanks.

Using MySQL but its pretty easy to change to others.

**Comment by kesar** [comment]
> Will this plugin can handle 10.000 TPS?

Not tested as right now you can't do 10k with nodeos. But it will depend pretty much of how fast its you database server

**Comment by liliyongleo** [comment]
Kesar, Great news!!!   if MongoDB is supported, much better. :-).     
Do you have the instructions on how to enable sql plugin using MySQL?  My email address is 21242620@qq.com
 Thanks a lot.

**Comment by newbieh4cker** [comment]
how can i build eosio with sql plugin enable??

**Comment by asiniscalchi** [comment]
Install [libsoci](http://soci.sourceforge.net/) in your system. 

on ubuntu:
$ sudo apt install libsoci-dev

**Comment by newbieh4cker** [comment]
@asiniscalchi 
thanks!! it build successful.

but when i try to run nodeos, it shows me "unable to find plugin: eosio::sql_db_plugin"

here is part of config.ini file

165 # Plugin(s) to enable, may be specified multiple times
166 # plugin =
167 #plugin = eosio::account_history_api_plugin
168 #plugin = eosio::account_history_plugin
169
170 plugin = eosio::chain_api_plugin
171 plugin = eosio::chain_plugin
172
173 plugin = eosio::history_api_plugin
174 plugin = eosio::history_plugin
175
176 plugin = eosio::http_client_plugin
177 plugin = eosio::http_plugin
178
179 #plugin = eosio::mongo_db_plugin
180 plugin = eosio::sql_db_plugin
181
182 plugin = eosio::net_api_plugin
183 plugin = eosio::net_plugin
184
185 plugin = eosio::producer_api_plugin
186 plugin = eosio::producer_plugin
187
188 plugin = eosio::wallet_api_plugin
189 plugin = eosio::wallet_plugin

**Comment by asiniscalchi** [comment]
could you paste the cmake output ?

**Comment by newbieh4cker** [comment]
@asiniscalchi  

deleting eos folder -> cloning new one from eosio github -> building solve "unable to find plugin" problem, But I'm facing new problem.


when I run below command
> nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::sql_db_plugin --sql_db-uri="mysql://dbname=eos"



shows me error

2124619ms thread-0   consumer.h:64                 run                  ] Consumer thread Start
2124620ms thread-1   sql_db_plugin.cpp:35          set_program_options  ] set_program_options
2124621ms thread-1   chain_plugin.cpp:208          plugin_initialize    ] initializing chain plugin
2124624ms thread-1   block_log.cpp:123             open                 ] Log is nonempty
2124624ms thread-1   block_log.cpp:141             open                 ] Index is nonempty
2124647ms thread-1   http_plugin.cpp:290           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
2124647ms thread-1   history_plugin.cpp:275        plugin_initialize    ] --filter-on * enabled. This can fill shared_mem, causing nodeos to stop.
2124647ms thread-1   sql_db_plugin.cpp:48          plugin_initialize    ] initialize
2124647ms thread-1   sql_db_plugin.cpp:56          plugin_initialize    ] connecting to mysql://dbname=eos
2124649ms thread-1   main.cpp:129                  main                 ] Access denied for user 'root'@'localhost' (using password: NO)
2124650ms thread-0   consumer.h:70                 run                  ] Consumer thread End


if this is cli mysql command.
I could run 'mysql -uroot -p' to input password, but since I'm running mysql as plugin.
I have no idea how to enter password.

**Comment by asiniscalchi** [comment]
this code is not in master branch yet.

**Comment by newbieh4cker** [comment]
@asiniscalchi  hmmm I see.

Is there any way(use git command or something else) to fetch latest commit version? 
https://github.com/EOSIO/eos/pull/3882/commits/bb361c081e91ada943001c674335c10bd8b193af

**Comment by newbieh4cker** [comment]
643559ms thread-2   actions_table.cpp:107         add                  ] Out of range value for column 'amount' at row 1

above error occurs, when starting nodeos with sql db plugin

**Comment by noprom** [comment]
Hi @asiniscalchi , do we have to modify the https://github.com/EOSIO/eos/blob/master/Docker/builder/Dockerfile
to enable the build of `sql_db_plugin`?
Or do we have a clear doc about how to build based on your github repo of branch `sql_plugin`:
https://github.com/NebulaProtocol/eos/tree/sql_plugin

I've modify the `Dockerfile` to make it build:

The Dockerfile:
```
FROM eosio/builder as builder
ARG branch=master
ARG symbol=SYS

RUN git clone -b $branch https://github.com/NebulaProtocol/eos.git --recursive \
    && cd eos && echo "$branch:$(git rev-parse HEAD)" > /etc/eosio-version \
    && cmake -H. -B"/tmp/build" -GNinja -DCMAKE_BUILD_TYPE=Release -DWASM_ROOT=/opt/wasm -DCMAKE_CXX_COMPILER=clang++ \
       -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/tmp/build  -DSecp256k1_ROOT_DIR=/usr/local -DBUILD_MONGO_DB_PLUGIN=true -DCORE_SYMBOL_NAME=$symbol \
    && cmake --build /tmp/build --target install && rm /tmp/build/bin/eosiocpp


FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install libsoci-dev openssl ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/lib/* /usr/local/lib/
COPY --from=builder /tmp/build/bin /opt/eosio/bin
COPY --from=builder /tmp/build/contracts /contracts
COPY --from=builder /eos/Docker/config.ini /
COPY --from=builder /etc/eosio-version /etc
COPY --from=builder /eos/Docker/nodeosd.sh /opt/eosio/bin/nodeosd.sh
ENV EOSIO_ROOT=/opt/eosio
RUN chmod +x /opt/eosio/bin/nodeosd.sh
ENV LD_LIBRARY_PATH /usr/local/lib
VOLUME /opt/eosio/bin/data-dir
ENV PATH /opt/eosio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
And the build command I use:
```
docker build -t noprom/eos:sql --build-arg branch=sql_plugin --build-arg symbol=EOS .
```
The build was successfully, but can not load the plugin when starting nodeos:
```
std::exception::what: unable to find plugin: eosio::sql_db_plugin
```

Look forward to your reply.

**Comment by kesar** [comment]
Can you check the output of the build? Perhaps you need to install also mysql-server / client libs.

You should see something like:

-- Soci found: Looking for plugins
--     * Plugin mysql found /usr/lib/x86_64-linux-gnu/libsoci_mysql.so.
--     * Plugin odbc found /usr/lib/x86_64-linux-gnu/libsoci_odbc.so.
--     * Plugin postgresql found /usr/lib/x86_64-linux-gnu/libsoci_postgresql.so.
--     * Plugin sqlite3 found /usr/lib/x86_64-linux-gnu/libsoci_sqlite3.so.
-- Database SQL plugin: enabled

**Comment by noprom** [comment]
Hi @kesar , that means we have to modify the builder Dockerfile right?
https://github.com/EOSIO/eos/blob/master/Docker/builder/Dockerfile

**Comment by noprom** [comment]
Hi @kesar , my build log:
```
Selecting previously unselected package libsoci-core3.2v5:amd64.
Preparing to unpack .../08-libsoci-core3.2v5_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-core3.2v5:amd64 (3.2.3-2ubuntu2) ...
Selecting previously unselected package libsoci-firebird3.2v5:amd64.
Preparing to unpack .../09-libsoci-firebird3.2v5_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-firebird3.2v5:amd64 (3.2.3-2ubuntu2) ...
Selecting previously unselected package libsoci-mysql3.2v5:amd64.
Preparing to unpack .../10-libsoci-mysql3.2v5_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-mysql3.2v5:amd64 (3.2.3-2ubuntu2) ...
Selecting previously unselected package libsoci-odbc3.2v5:amd64.
Preparing to unpack .../11-libsoci-odbc3.2v5_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-odbc3.2v5:amd64 (3.2.3-2ubuntu2) ...
Selecting previously unselected package libsoci-postgresql3.2v5:amd64.
Preparing to unpack .../12-libsoci-postgresql3.2v5_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-postgresql3.2v5:amd64 (3.2.3-2ubuntu2) ...
Selecting previously unselected package libsoci-sqlite3-3.2v5:amd64.
Preparing to unpack .../13-libsoci-sqlite3-3.2v5_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-sqlite3-3.2v5:amd64 (3.2.3-2ubuntu2) ...
Selecting previously unselected package libsoci-dev.
Preparing to unpack .../14-libsoci-dev_3.2.3-2ubuntu2_amd64.deb ...
Unpacking libsoci-dev (3.2.3-2ubuntu2) ...
Setting up libsoci-core3.2v5:amd64 (3.2.3-2ubuntu2) ...
Setting up libsoci-odbc3.2v5:amd64 (3.2.3-2ubuntu2) ...
Setting up libsoci-firebird3.2v5:amd64 (3.2.3-2ubuntu2) ...
Setting up libsoci-postgresql3.2v5:amd64 (3.2.3-2ubuntu2) ...
Setting up libsoci-mysql3.2v5:amd64 (3.2.3-2ubuntu2) ...
Setting up libsoci-sqlite3-3.2v5:amd64 (3.2.3-2ubuntu2) ...
Setting up libsoci-dev (3.2.3-2ubuntu2) ...
--     * Plugin mysql found /usr/lib/x86_64-linux-gnu/libsoci_mysql.so.
--     * Plugin odbc found /usr/lib/x86_64-linux-gnu/libsoci_odbc.so.
--     * Plugin postgresql found /usr/lib/x86_64-linux-gnu/libsoci_postgresql.so.
--     * Plugin sqlite3 found /usr/lib/x86_64-linux-gnu/libsoci_sqlite3.so.
-- Database SQL plugin: enabled
```

But when I run nodeos, I got the error:
```
/opt/eosio/bin/nodeos: error while loading shared libraries: libsoci_core.so.3.2: cannot open shared object file: No such file or directory
```
Can you look into that?

**Comment by kesar** [comment]
> Can you look into that?

That's weird, perhaps a make install missing ?

**Comment by newbieh4cker** [comment]
@kesar 

Hello kesar.
How can I pull your latest commit?

**Comment by liliyongleo** [comment]
hi, I got an error with sql_plugin. and it will crash the nodeos process, and core dump. 
given that eosio.token contract is deployed by eosio, and user eosio create user1 account, and user user1 create another user2 account. after that. we tried to transfer EOS from user1 to user2, it will lead to some problem in mysql, something related to foreign-key. 
default

please help. Thanks.

**Comment by newbieh4cker** [comment]
@kesar 

When I run below command, "eosio" accounts spends '1.0 BOT token' for tester user, to give cpu,net,ram bandwidth.

After running command with 'cleos get account eosio', I can get precise balance. But When I query balance from mysql(using sql_db_plugin) balance is not correct.

it looks like your 'sql_db_plugin" plugin doesn't catch 'cleos system' command. 

Do you have plan to fix  this? Or am I doing something wrong?

>cleos system newaccount eosio tester EOS5uVevzEMdDLEkyF26mFkxg5dfXnkiBVe7h8WSS9tJzaVjYsjgd EOS5uVevzEMdDLEkyF26mFkxg5dfXnkiBVe7h8WSS9tJzaVjYsjgd --stake-net "0.3 BOT" --stake-cpu "0.3 BOT" --buy-ram "0.4 BOT"

**Comment by dbarobin** [comment]
Some sql error exists in the nodeos log, and the nodeos force quit. Yet I have to delete blocks file of EOS blockchain and eos database in MySQL to force resync, how to avoid and solve this problem?

When sync to `zhengjinhua1`, and nodoes exit. The log as follows:

``` bash
terminate called after throwing an instance of 'soci::mysql_soci_error'                                                                            
  what():  Out of range value for column 'amount' at row 1 while executing "INSERT INTO tokens(account, amount, symbol) VALUES (:ac, :am, :as) " with :ac="zhengjinhua1", :am=1e+10, :as="UXB".  
```

The amount filed of tokens table defines double(14,4), but 1e+10 means 10 billion, it exceed the maximum. It should change to double(64,4), the command as follows:

``` sql
ALTER TABLE tokens CHANGE amount amount double(64,4) DEFAULT NULL;
```

**Comment by AUTHAI-bit** [comment]
0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347

**Comment by AUTHAI-bit** [comment]
0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347

**Comment by ericiles** [comment]
@asiniscalchi the CICD docker images have been updated, and the failing tests have been re-ran. Looks like everything has passed.

**Comment by newbieh4cker** [comment]
@kesar  
as @trungtt1981  mentioned.

'eosio::chain::abi_serialization_deadline_exception' error occurs

**Comment by trungtt1981** [comment]
@newbieh4cker 
@kesar 
@asiniscalchi 
If possible, please inform me the revision which I can run the nodeos client without this kind of exception.
I see that the https://eostracker.io/ is running well.
So, which revision is it using?

Thanks

**Comment by trungtt1981** [comment]
@asiniscalchi 
Thanks very much for your fix of this bug.
It works now fine!
Cheers

**Comment by asiniscalchi** [comment]
@ericiles is there any way to speed up the merging into master ?
This pull request makes me do nightmares.

**Comment by mirror222** [comment]
@trungtt1981
could you please kindly tell me how to fix the "eosio::chain::abi_serialization_deadline_exception' bug?

**Comment by heifner** [comment]
@asiniscalchi @kesar We just discussed this PR. First, we would like to thank you for your support of EOSIO! It really is much appreciated. Our hope was (and still is) to provide easier plugin integration support.

You may have noticed that there is some github repro reorg in progress. As such we would like to remove this plugin from the EOSIO/eos repro and ask you to host it separately. Either by itself or in a fork of eos, whatever you like and is the easiest.

In the future we actually hope to provide similar seperation for the other plugins. During this process please help us with what is needed so external plugins like the sql_plugin can be integrated by users as easily as possible. We are hoping you will help us by being a "guinea pig" for this process.

**Comment by kesar** [comment]
sounds good 👍

**Comment by newbieh4cker** [comment]
@kesar 

what is isolated github address for sql_db_plugin??

**Comment by trungtt1981** [comment]
@newbieh4cker 
https://github.com/NebulaProtocol/eos/tree/sql_plugin

**Comment by cppfuns** [comment]
1250174ms thread-0   wasm_interface.cpp:929        eosio_assert         ] message: refund request not found 
1250192ms thread-0   controller.cpp:625            push_scheduled_trans ] 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: refund request not found
    {"s":"refund request not found"}
    thread-0  wasm_interface.cpp:930 eosio_assert
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one
terminate called after throwing an instance of 'eosio::chain::abi_serialization_deadline_exception'
Aborted

**Pull request closed without merging**
