### PR TITLE
acceptor thread-safety

### PR DESCRIPTION
**Pull request by heifner**
## Change Description

- `boost::asio::acceptor` is not thread safe; protect use with a `mutex`

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by spoonincode** [comment]
Where was the problem? Only at shutdown?

**Comment by heifner** [comment]
@spoonincode This was an observation, not any known bug. Although #7639 might be this.

**Comment by heifner** [comment]
Note since it is `async_accept` it is possible for multiple strands to attempt to use the same `acceptor` at the same time.

**Comment by spoonincode** [comment]
>Note since it is async_accept it is possible for multiple strands to attempt to use the same acceptor at the same time.

I'm trying to figure out how that works. It seems like there can only be one `async_accept` outstanding because only after the `async_accept` completes is `start_listen_loop` called again (which does the next `async_accept`)

**Comment by heifner** [comment]
I missed that `start_listen_loop` was inside the lambda. So yes, this is not needed.

**Comment by spoonincode** [comment]
@heifner there might still technically be a problem at shutdown. Maybe the closing of the acceptor should be after the thread_pool is shut down.

**Comment by heifner** [comment]
Agreed. I have another net_plugin PR I'll add that to.

**Pull request closed without merging**
