### PR TITLE
Different, configurable contract execution times

### PR DESCRIPTION
**Pull request by brianjohnson5972**
#524 

Added 3 configuration parameters:

trans-exectution-time - in chain_plugin, used for push_transaction and accept_transaction

rcvd-block-trans-exectution-time - in chain_plugin, used for push_block, accept_block, and chain_controller initialization of block and replay

create-block-trans-execution-time - in producer_plugin for maybe_produce_block

wasm_interface::init still uses fixed value - (figured you would comment in this review if that should have its own config value)

Made default values to be used in unit tests.

### CODE REVIEW

**Comment by bytemaster** [comment]
I had envisioned these would be properties on the controller and not something passed into every push()/apply() call.

I would have used the skip_flags (which shouldn't really be called skip flags) to indicate the "mode" and then based on the mode the WASM interface can pick the proper runtime.

**Comment by brianjohnson5972** [comment]
I will put all the different execution times in chain_plugin and pass into chain_controller.

**Comment by brianjohnson5972** [comment]
@bytemaster If I use the skip flags, the issue is that I have 3 states to convey in a flag, so I will have the ambiguity of being able to set 3 flags, where only one of them will be used.

Also, I'm assuming that you want _skip_flags used until wasm_interface needs to be called.

I was passing the time to address the eventual issue that we will have once we add multi-threading, but I guess we will need to address the same issue with _skip_flags anyways.

**Comment by brianjohnson5972** [comment]
Another ambiguity with the flags is that when we get to calling wasm_interface::get().apply(...), at least one of those flags needs to be set, so I guess I will default to the shortest duration if one isn't set.

**Comment by brianjohnson5972** [comment]
Made requested changes and squashed commits.

**Pull request merged**
