### PR TITLE
Allow rodeos to recover from kill-9

### PR DESCRIPTION
**Pull request by heifner**
## Change Description

- If rodeos crashes (kill -9) then the eosvmoc code cache is invalid. If unable to open code cache remove the cache and try again. This allows rodeos to recover from a kill -9.
- Enhance the existing rodeos test to add a kill -9 to rodeos and verify it recovers correctly.
- Removed option -max-retained-history-files since it is currently broken

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [x] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by swatanabe-b1** [comment]
What happens if it's dirty because another rodeos process is currently using it?

**Comment by heifner** [comment]
> What happens if it's dirty because another rodeos process is currently using it?

BadThings(TM). Any recommendations on how to avoid that?

**Comment by spoonincode** [comment]
Really? My first guess would have been it's okay because removing a file doesn't invalidate the existing open handles to that file (and I don't believe OC ever re-opens its cache file to encounter it switched out from under it).

I do wonder if OC should simply always do this on its own instead of farming it out externally. But at this point since rodeos future is kinda uncertain, not sure worth over thinking it...

**Comment by heifner** [comment]
> Really? My first guess would have been it's okay because removing a file doesn't invalidate the existing open handles to that file (and I don't believe OC ever re-opens its cache file to encounter it switched out from under it).

I didn't test the scenario. Let me test it and see what happens.

**Comment by heifner** [comment]
> I didn't test the scenario. Let me test it and see what happens.

```
warn  2021-03-23T15:58:57.754 thread-0  wasm_ql_plugin.cpp:139        plugin_initialize    ] 13 N2b18chain_kv9exceptionE: database::database: rocksdb::DB::Open: IO error: While lock file: /Users/kevin.heifner/ext/develop-boxed-2.1/cmake-build-relwithdebinfo/var/lib/rodeos/rocksdb/LOCK: Resource temporarily unavailable
rethrow database::database: rocksdb::DB::Open: IO error: While lock file: /Users/kevin.heifner/ext/develop-boxed-2.1/cmake-build-relwithdebinfo/var/lib/rodeos/rocksdb/LOCK: Resource temporarily unavailable:
    {"what":"database::database: rocksdb::DB::Open: IO error: While lock file: /Users/kevin.heifner/ext/develop-boxed-2.1/cmake-build-relwithdebinfo/var/lib/rodeos/rocksdb/LOCK: Resource temporarily unavailable"}
    thread-0  wasm_ql_plugin.cpp:139 plugin_initialize
```

**Comment by swatanabe-b1** [comment]
The file is opened before exit to reset the dirty flag.  I think the following is possible:
- start rodeos1
- start rodeos2 - creates a new file
- exit rodeos1 cleanly - resets dirty flag in the file created by rodeos2
- kill -9 rodeos2
- start rodeos3 - dirty flag _not_ set 💥

**Comment by swatanabe-b1** [comment]
There's also a race on startup, but that's a problem that already exists and it's much less likely.  I usually run into this situation when I forget that I'm already running rodeos, which implies a significant time lapse.

**Comment by heifner** [comment]
> The file is opened before exit to reset the dirty flag. I think the following is possible:

Not sure what more we can do here except: "Doctor it hurts when I do ...".
Open to suggestions.

**Comment by heifner** [comment]
> > The file is opened before exit to reset the dirty flag. I think the following is possible:
> 
> Not sure what more we can do here except: "Doctor it hurts when I do ...".
> Open to suggestions.

I guess we could just ALWAYS remove any existing eosvmoc cache on startup. Thoughts?

**Comment by spoonincode** [comment]
I still need to refactor the OC code cache so it can work properly on a `noexec` filesystem (mostly meaning adding the ability to do heap/locked for the OC code cache). Maybe at that point can eliminate any re-opening and eliminate that race.

**Review by spoonincode — APPROVED** [review]

**Review by swatanabe-b1 — APPROVED** [review]

**Pull request merged**
