### PR TITLE
[doc][develop] Add resource_monitor_plugin documentation

### PR DESCRIPTION
**Pull request by linhuang-blockone**
ion for resource_monitor_plugin

## Change Description

https://github.com/EOSIO/eos/issues/9839
https://github.com/EOSIO/eos/issues/10105
https://github.com/EOSIO/eos/issues/10106
https://github.com/EOSIO/eos/issues/10107

https://blockone.atlassian.net/browse/EPE-808
https://blockone.atlassian.net/browse/EPE-809

The corresponding PR for 2.1.x is https://github.com/EOSIO/eos/pull/10307.

Add documentation for resource_monitor_plugin.

## Change Type
**Select *ONE*:**
- [x] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [x] Documentation Additions

### CODE REVIEW

**Review by matthewdarwin — COMMENTED** [review]
This documentation does not address the comment in https://github.com/EOSIO/eos/issues/10106, specifically about how each data volume is monitored independently.

**Comment by linhuang-blockone** [comment]
> This documentation does not address the comment in #10106, specifically about how each data volume is monitored independently.

"the file systems" in the following quoted text are data volumes. Will reword to make it more specifically. "it measures the space used by the file systems mounted by `data-dir`, `state-dir`, `blocks-log-dir`, `snapshots-dir`, `state-history-dir`, and `trace-dir`."

**Review by matthewdarwin — APPROVED** [review]

**Comment by matthewdarwin** [comment]
Can the config options printed by nodeos also be improved similarly?  (this would also require a nodeos code change presumably). Also why is it written %5 instead of 5%?

```
Config Options for eosio::resource_monitor_plugin:
+
+  --resource-monitor-interval-seconds arg (=2)
+                                        Time in seconds between two consecutive
+                                        checks of space usage. Should be
+                                        between 1 and 300.
+  --resource-monitor-space-threshold arg (=90)
+                                        Threshold in terms of percentage of used
+                                        space vs total space. If the used space is
+                                        within `%5` of the threshold, a warning is
+                                        generated. If used space is above the
+                                        threshold and `resource-monitor-not-shutdown-on-threshold-exceeded`
+                                        is enabled, a graceful shutdown is initiated;
+                                        otherwise a warning will be continuously
+                                        printed out.
+                                        The value should be between 6 and 99.
+  --resource-monitor-not-shutdown-on-threshold-exceeded
+                                        A switch used to indicate `nodeos` will "not"
+                                        shutdown when threshold is exceeded. When not
+                                        set, `nodeos` will shutdown.
+  --resource-monitor-warning-interval arg (=30)
+                                        Number of monitor intervals between
+                                        which a warning is displayed.
+                                        For example,
+                                        if `resource-monitor-warning-interval`
+                                        is set to `10` and 
+                                        `resource-monitor-interval-seconds` is 2, 
+                                        a warning will be displayed every 20 seconds,
+                                        even though the space usage is checked every
+                                        2 seconds.
+                                        This is used to throttle the number of
+                                        warnings in the `nodeos` log file.
+                                        Should be between 1 and 450.
```

**Comment by linhuang-blockone** [comment]
> Can the config options printed by nodeos also be improved similarly? (this would also require a nodeos code change presumably). Also why is it written %5 instead of 5%?
> 
> ```
> Config Options for eosio::resource_monitor_plugin:
> +
> +  --resource-monitor-interval-seconds arg (=2)
> +                                        Time in seconds between two consecutive
> +                                        checks of space usage. Should be
> +                                        between 1 and 300.
> +  --resource-monitor-space-threshold arg (=90)
> +                                        Threshold in terms of percentage of used
> +                                        space vs total space. If the used space is
> +                                        within `%5` of the threshold, a warning is
> +                                        generated. If used space is above the
> +                                        threshold and `resource-monitor-not-shutdown-on-threshold-exceeded`
> +                                        is enabled, a graceful shutdown is initiated;
> +                                        otherwise a warning will be continuously
> +                                        printed out.
> +                                        The value should be between 6 and 99.
> +  --resource-monitor-not-shutdown-on-threshold-exceeded
> +                                        A switch used to indicate `nodeos` will "not"
> +                                        shutdown when threshold is exceeded. When not
> +                                        set, `nodeos` will shutdown.
> +  --resource-monitor-warning-interval arg (=30)
> +                                        Number of monitor intervals between
> +                                        which a warning is displayed.
> +                                        For example,
> +                                        if `resource-monitor-warning-interval`
> +                                        is set to `10` and 
> +                                        `resource-monitor-interval-seconds` is 2, 
> +                                        a warning will be displayed every 20 seconds,
> +                                        even though the space usage is checked every
> +                                        2 seconds.
> +                                        This is used to throttle the number of
> +                                        warnings in the `nodeos` log file.
> +                                        Should be between 1 and 450.
> ```

Thanks for spotting %5. A typo. Will change. Will update options printed by nodeos in another PR.

**Review by bogniq — APPROVED** [review]

**Pull request merged**
