### PR TITLE
eosc unsigned transactions

### PR DESCRIPTION
**Pull request by elmato**
Simple example of using eosc to multisig a token transfer

```bash
# Private key: 5KedEKNC14q9uj5uWyLBunKbenokXseQaXiE6k2AGZZhskBxdrV
# Public key: EOS5vNnn5fym9FJbTMT8AvSTY13XQsoer2HDBup33uespnDhLPipG
eosc create account inita acc1 EOS5vNnn5fym9FJbTMT8AvSTY13XQsoer2HDBup33uespnDhLPipG EOS5vNnn5fym9FJbTMT8AvSTY13XQsoer2HDBup33uespnDhLPipG

# Private key: 5K1wrWCTvaEoxczzceDzSHEwUL97tdWFnGQpZpjrgjxqWDkty1M
# Public key: EOS7yvrzX9B2h5UUyu765y2BHmY5NSHQxCZgf1ypuRssCdG4PXzWC
eosc create account inita acc2 EOS7yvrzX9B2h5UUyu765y2BHmY5NSHQxCZgf1ypuRssCdG4PXzWC EOS7yvrzX9B2h5UUyu765y2BHmY5NSHQxCZgf1ypuRssCdG4PXzWC

# Private key: 5JFzjHMtsbodCkc9rwmbWscKbVZ8zjsMHPMrAw8DWoG8r3rCmdo
# Public key: EOS8juGUoC7oQbMQ7aCmTq1659U9Di4U4sfihKeyNay99SW81qRkn
eosc create account inita test EOS8juGUoC7oQbMQ7aCmTq1659U9Di4U4sfihKeyNay99SW81qRkn EOS8juGUoC7oQbMQ7aCmTq1659U9Di4U4sfihKeyNay99SW81qRkn

# import private key to allow changing the active permission of test account 
eosc wallet import 5JFzjHMtsbodCkc9rwmbWscKbVZ8zjsMHPMrAw8DWoG8r3rCmdo

# change test@active permission to be 2of2 (both acc1@active and acc2@active)
eosc set account permission test active '{"threshold" : 100, "keys" : [], "accounts" : [{"permission":{"account":"acc2","permission":"active"},"weight":50},{"permission":{"account":"acc1","permission":"active"},"weight":50}]}' owner

# deploy currency contract
eosc create account inita currency EOS8juGUoC7oQbMQ7aCmTq1659U9Di4U4sfihKeyNay99SW81qRkn EOS8juGUoC7oQbMQ7aCmTq1659U9Di4U4sfihKeyNay99SW81qRkn
eosc set contract currency ~/dev/eos/build/contracts/currency/currency.wast ~/dev/eos/build/contracts/currency/currency.abi

# send 100 tokens to test account
eosc push message currency transfer '{"from":"currency","to":"test","quantity":100}' -S currency,test -p currency@active

# verify that we cant transfer from test account
eosc push message currency transfer '{"from":"test","to":"currency","quantity":5}' -S currency,test -p test@active

# generate an unsigned transaction that transfers 5 tokens from "test" to "currency"
eosc push message -s -d -x 120 currency transfer '{"from":"test","to":"currency","quantity":5}' -S currency,test -p test@active > tx_unsigned.json
cat tx_unsigned.json
{
  "ref_block_num": 760,
  "ref_block_prefix": 293222988,
  "expiration": "2017-12-04T08:14:26",
  "scope": [
    "currency",
    "test"
  ],
  "read_scope": [],
  "messages": [{
      "code": "currency",
      "type": "transfer",
      "authorization": [{
          "account": "test",
          "permission": "active"
        }
      ],
      "data": "000000000090b1ca0000001e4d75af460500000000000000"
    }
  ],
  "signatures": []
}

# acc1@active sign
eosc sign tx_unsigned.json -k 5KedEKNC14q9uj5uWyLBunKbenokXseQaXiE6k2AGZZhskBxdrV > tx_partial.json
cat tx_partial.json
{
  "ref_block_num": 760,
  "ref_block_prefix": 293222988,
  "expiration": "2017-12-04T08:14:26",
  "scope": [
    "currency",
    "test"
  ],
  "read_scope": [],
  "messages": [{
      "code": "currency",
      "type": "transfer",
      "authorization": [{
          "account": "test",
          "permission": "active"
        }
      ],
      "data": "000000000090b1ca0000001e4d75af460500000000000000"
    }
  ],
  "signatures": [
    "20024f73477f1a570fbebe91eec7a36a4be33ebf8cd1b8b31732cc67c99a5b880b792b8aeb0c2e00ab2a3eb4cee2639ac7cb163c994ab1772021db23e5b6df5c95"
  ]
}

# acc2@active sign
eosc sign tx_partial.json -k 5K1wrWCTvaEoxczzceDzSHEwUL97tdWFnGQpZpjrgjxqWDkty1M > tx_signed.json
cat tx_signed.json
{
  "ref_block_num": 760,
  "ref_block_prefix": 293222988,
  "expiration": "2017-12-04T08:14:26",
  "scope": [
    "currency",
    "test"
  ],
  "read_scope": [],
  "messages": [{
      "code": "currency",
      "type": "transfer",
      "authorization": [{
          "account": "test",
          "permission": "active"
        }
      ],
      "data": "000000000090b1ca0000001e4d75af460500000000000000"
    }
  ],
  "signatures": [
    "20024f73477f1a570fbebe91eec7a36a4be33ebf8cd1b8b31732cc67c99a5b880b792b8aeb0c2e00ab2a3eb4cee2639ac7cb163c994ab1772021db23e5b6df5c95",
    "2064c65a979a9c081dc5f0a1f34d43bd4fb4245298eeb9d5fb15462b43ef6837c56f814090e697a389162cd4ac5f3d33bfe762e68d7289188e0307f23cd05ebd52"
  ]
}


# broadcast signed transaction
eosc push transaction tx_signed.json
```

### CODE REVIEW

**Comment by dskvr** [comment]
Beautiful <3

**Comment by SheldonHH** [comment]
Great working, 
Here is one issue and one question when I tried to replace the code `main.cpp` and run the command.
1. I encounter this when I tried to `push transactions`
image


2. Why cannot `transfer` tokens from `test` to `currency` in normal way after assign multisig to `test`?
```
# verify that we cant transfer from test account
eosc push message currency transfer '{"from":"test","to":"currency","quantity":5}' -S currency,test -p test@active

```

**Comment by elmato** [comment]
@SheldonHH 

1) Remember that the transaction expiration time is set when you create the unsigned TX (**-x 120** in the example). If the following steps (signing+pushing) takes more than 2 minutes, the transaction may get expired.

2) That's because the wallet (eosd) doesn't have the private keys for **acc1@active** and **acc2@active**, hence it cannot sign the TX with the required keys.

**Comment by errord** [comment]
who

**Comment by dskvr** [comment]
@elmato What is the max expiration time that can be set?

**Comment by elmato** [comment]
suppressed by #1265

**Pull request closed without merging**
