### PR TITLE
relaxing the on_notify constraint to *

### PR DESCRIPTION
**Pull request by nksanthosh**
I am relaxing the on_notify constraint back to *

This issue was first reported against EOSIO.CDT 1.6.1 https://github.com/EOSIO/eosio.cdt/issues/497 and has been fixed since EOSOIO.CDT 1.6.2.

// eosio.cdt 1.6.1 has a problem with "* ::notify" so hardcode to tester1 for now.
// TODO: Change it back to "* ::notify" when the bug is fixed in eosio.cdt.
[[eosio::on_notify("tester1::notify")]]

Redoing this PR from a branch instead of https://github.com/EOSIO/eos/pull/9229 as that seems to have continuing build issues (from a fork)

## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by nksanthosh** [comment]
> Copying over @b1bart comment from other PR:
> 
> The test contracts are all pre-built in the repository. I would expect that this had a wasm-level change even if it did not change the test-facing interface.
> 
> Did the output .wasm and .abi of -DEOSIO_COMPILE_TEST_CONTRACTS=True not change from the ones checked in?

yes! will address that.

**Comment by nksanthosh** [comment]
> Copying over @b1bart comment from other PR:
> 
> The test contracts are all pre-built in the repository. I would expect that this had a wasm-level change even if it did not change the test-facing interface.
> 
> Did the output .wasm and .abi of -DEOSIO_COMPILE_TEST_CONTRACTS=True not change from the ones checked in?

Thanks @b1bart and @heifner ! Built the unit tests and verified that .wasm has changed but the .abi has not. Verified wasm changes both via hex compare and eosio-wasm2wast disassembler. Please let me know if there is any more feedback.

**Comment by heifner** [comment]
The wasm needs to be added to this PR, it is committed in the repo.

**Comment by nksanthosh** [comment]
> The wasm needs to be added to this PR, it is committed in the repo.

Done added the wasm file

**Pull request merged**
