### PR TITLE
Fix #8624

### LINKED ISSUE #8624: Documentation says wavm is supported for wasm-runtime (it is not), doesn't mention eos-vm
re: https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_plugin/index

The formatting of this page leaves much to be desired as the wrapping makes things unreadable.
However, the point of this issue is to say that the documentation is out of date.

It says:
```
--wasm-runtime wavm/wabt              Override default WASM runtime
```

* `wavm` was removed in 2.0.
* `wasm-runtime` = eos-vm-jit is not mentioned.
* `eos-vm-oc-enable` is not mentioned.

See also https://github.com/EOSIO/eos/issues/8620, where there are significant detail missing about when to use (and not use) these options.

Block.one spends quite a bit of time talking to people in telegram explaining things, but that knowledge is not always captured in the documentation.  Then people not familiar with discussion make mistakes because they can't find how to use stuff properly.

### PR DESCRIPTION
**Pull request by dixia**
## Change Description

Fix issue #8624

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by dixia** [comment]
Fix #8624

**Comment by lparisc** [comment]
We pull the valid options from the `nodeos --help`, which also needs further clarification:
```
  --wasm-runtime runtime                Override default WASM runtime
```
@dixia The runtime options are: `wabt` (default), `eos-vm`, `eos-vm-jit`, `eos-vm-oc` (the latter not valid on MacOS). I would replace with:
```
  --wasm-runtime wabt|eos-vm|eos-vm-jit|eos-vm-oc
                                        Override default WASM runtime (wabt)
                                        (eos-vm-oc not supported on MacOS)
```
@arhag Please note suggested `nodeos --help` message for `--wasm-runtime`.

**Comment by dixia** [comment]
hi all, this is to update the out-of-date doc but not to update the code which has actual `nodeos --help` message

happy to create a separate Issue/PR to update the code as well but that should be done separately

**Comment by lparisc** [comment]
@dixia please note corrected nodeos options:

```
  --wasm-runtime eos-vm|eos-vm-jit      Override default WASM runtime (wabt)
  --eos-vm-oc-enable                    Enable optimized compilation
```

**Comment by dixia** [comment]
> Should be:
> 
> ```
>   --wasm-runtime eos-vm|eos-vm-jit      Override default WASM runtime (wabt)
>   --eos-vm-oc-enable                    Enable optimized compilation
> ```



> Should be:
> 
> ```
>   --wasm-runtime eos-vm|eos-vm-jit      Override default WASM runtime (wabt)
>   --eos-vm-oc-enable                    Enable optimized compilation
> ```

Could you

**Comment by sunshineveg** [comment]
Set up a separate PR for the code issue and close the documentation issue.

**Pull request merged**
