### PR TITLE
3747 fix some of the test cases in block_tests

### PR DESCRIPTION
**Pull request by taokayan**
#3747

### CODE REVIEW

**Comment by bytemaster** [comment]
Could you please describe what is fixed and/or what is tested?

**Comment by taokayan** [comment]
Hi, this is a short description:

Fixed/ported tests:
```
schedule_test
trx_variant test
trx_uniqueness test
invalid_expiration test
transaction_expiration test
invalid_tapos test
irrelevant_auth test
no_auth test
name_test
```
Partial ported tests:
```last_irreversible_update_bug_test: since LIB logic was redesigned, the test might not related to the original bug
schedule_test: This test the database close & reopen. but due to the LIB logic changed, head is now equal to lib + 1.```

tests that not yet ported, unable or difficult to be ported:
```
push_block: too trivial, this exist in many other tests
push_invalid_block, order_dependent_transactions: no longer valid as region/cycles are already removed
no_network, simple_network, forked_network, sleepy_db, irrelevant_sig_soft_check, irrelevant_sig_hard_check, block_id_sig_independent, get_required_keys: need more time to be ported since we might need to fix eosio::testing::tester_network

```

**Comment by heifner** [comment]
@taokayan @andriantolie Where are we with this PR? Can it be closed or are there useful tests here that should be merged?

**Comment by taokayan** [comment]
hi @heifner I think this can be closed since most of the test cases are no longer valid or useful.

**Pull request closed without merging**
