### PR TITLE
Allow p2p incomming connections when in read only mode

### PR DESCRIPTION
**Pull request by elmato**
## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by heifner** [comment]
Can you provide your use case for enabling this behavior. The point of a read only node is so it can feed plugins not to do any validation on transactions/blocks.

**Comment by elmato** [comment]
The use case is to offer a read-only peering mode where clients can sync to the chain but they are not allowed to to push transactions using that channel.

This is useful for some sidechains that wants to let user get in sync with the chain, but they have to push transactions through over another channel (UI / RPC)

**Comment by heifner** [comment]
> The use case is to offer a read-only peering mode where clients can sync to the chain but they are not allowed to to push transactions using that channel.
> 
> This is useful for some sidechains that wants to let user get in sync with the chain, but they have to push transactions through over another channel (UI / RPC)

Can't they just not load the `chain_api_plugin` ?

**Comment by swatanabe-b1** [comment]
Can we close this?  It should be resolved by https://github.com/EOSIO/eos/pull/8743, right?

**Pull request closed without merging**
