### PR TITLE
Build Script Changes + BATS Testing

### PR DESCRIPTION
**Pull request by NorseGaud**
### Summary of changes
- Users who have installed gcc-c++ or clang on their machine, but don't have a high enough version, then say yes to allowing us to build clang8 for them, no longer have to use -P option and can get away with no options/flags when running the build script.
- BATS-CORE is being used for bash testing. This will allow us to ensure bash scripts function as they should for users. It's perfect regression testing and consistency. (see tests/bash-bats/README.md)
- DRYRUN and VERBOSE environment variables supported for troubleshooting (even outside of bats).
- All scripts we use to build, install, and uninstall, have been updated with .bash filename to indicate bash is required + `#!/usr/bin/env bash` in-case non-standard bash is being used.
- All scripts we use to build, install, and uninstall, have been updated for better user experience (prompts + output + set -eo pipefail for immediate exit on failure)
- ALL Dep install scripts are now using external files and better checks for existence
- Using a .environment file containing all ENVs for flexibility
- Installation location is now ${HOME}/eosio/1.8.0, where 1.8.0/the version is pulled from REPO_ROOT/CMakeLists.txt (community requested)
  - CMakeLists modification to remove CMAKE_INSTALL_PREFIX/eosio and use the new install location instead (so we get ~/eosio/1.8.0/bin/nodeos instead of ~/eosio/1.8.0/opt/eosio/bin/nodeos )
- Use of helpers for functions used throughout build scripts to make things less messy to update/fix

1. https://github.com/EOSIO/eos/issues/6931 : Prompts are now humane + install into version specific folder
2. https://github.com/EOSIO/eos/issues/7120 : Centos 7 will now use sudo for yum commands if $(whoami) = root
3. https://github.com/EOSIO/eos/issues/7262 : New directory structure should fix this
4. https://github.com/EOSIO/eos/issues/7260 : New logic should prevent this from being a problem
5. https://github.com/EOSIO/eos/issues/7232 : User prompts if missing which or c++ (and not using -P).

### CODE REVIEW

**Comment by NorseGaud** [comment]
Amazon Linux 2 ---------------------------------
`-y -P -m`: Works
( yum install gcc-c++ ) `-y`

```

[ 84%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/abi_serializer.cpp.o
cd /eos/build/libraries/chain && /usr/bin/c++  -DBOOST_ASIO_DISABLE_STD_EXPERIMENTAL_STRING_VIEW -I/eos/libraries/chain/include -I/eos/build/libraries/chain/include -I/eos/libraries/chain/../wasm-jit/Include -I/eos/libraries/wabt -I/eos/build/libraries/wabt -I/eos/libraries/fc/include -I/root/eosio/1.9/src/boost_1_67_0/include -I/eos/libraries/fc/vendor/websocketpp -I/eos/libraries/fc/secp256k1/upstream -I/eos/libraries/fc/secp256k1/upstream/include -I/eos/libraries/chainbase/include -I/eos/libraries/wasm-jit/Source/Runtime/../../../chain/include -I/eos/libraries/softfloat/source/include -I/eos/libraries/softfloat/source/8086-SSE -I/eos/libraries/softfloat/build/Linux-x86_64-GCC -I/eos/libraries/builtins -I/eos/libraries/builtins../softfloat/source/include  -Wall -O3 -DNDEBUG   -pthread -std=gnu++1z -o CMakeFiles/eosio_chain.dir/abi_serializer.cpp.o -c /eos/libraries/chain/abi_serializer.cpp
In file included from /eos/libraries/chain/include/eosio/chain/database_utils.hpp:9:0,
                 from /eos/libraries/chain/include/eosio/chain/code_object.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/wasm_interface.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/config.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/block_timestamp.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_header.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_header_state.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_state.hpp:7,
                 from /eos/libraries/chain/include/eosio/chain/controller.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/wasm_eosio_validation.hpp:5,
                 from /eos/libraries/chain/wasm_eosio_validation.cpp:2:
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float32_t to_softfloat32(float)':
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float32_t*>(&f);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float64_t to_softfloat64(double)':
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float64_t*>(&d);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float from_softfloat32(float32_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:302:39: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float*>(&f);
                                       ^
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'double from_softfloat64(float64_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:305:40: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<double*>(&d);
                                        ^
In file included from /eos/libraries/chain/include/eosio/chain/database_utils.hpp:9:0,
                 from /eos/libraries/chain/include/eosio/chain/code_object.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/wasm_interface.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/webassembly/common.hpp:3,
                 from /eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:5,
                 from /eos/libraries/chain/wasm_eosio_injection.cpp:2:
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float32_t to_softfloat32(float)':
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float32_t*>(&f);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float64_t to_softfloat64(double)':
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float64_t*>(&d);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float from_softfloat32(float32_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:302:39: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float*>(&f);
                                       ^
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'double from_softfloat64(float64_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:305:40: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<double*>(&d);
                                        ^
In file included from /eos/libraries/chain/include/eosio/chain/database_utils.hpp:9:0,
                 from /eos/libraries/chain/include/eosio/chain/code_object.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/wasm_interface.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/config.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/block_timestamp.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_header.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_header_state.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_state.hpp:7,
                 from /eos/libraries/chain/include/eosio/chain/controller.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/apply_context.hpp:6,
                 from /eos/libraries/chain/apply_context.cpp:2:
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float32_t to_softfloat32(float)':
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float32_t*>(&f);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float64_t to_softfloat64(double)':
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float64_t*>(&d);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float from_softfloat32(float32_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:302:39: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float*>(&f);
                                       ^
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'double from_softfloat64(float64_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:305:40: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<double*>(&d);
                                        ^
In file included from /eos/libraries/chain/include/eosio/chain/database_utils.hpp:9:0,
                 from /eos/libraries/chain/include/eosio/chain/code_object.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/wasm_interface.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/config.hpp:6,
                 from /eos/libraries/chain/include/eosio/chain/block_timestamp.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block_header.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/block.hpp:2,
                 from /eos/libraries/chain/include/eosio/chain/trace.hpp:9,
                 from /eos/libraries/chain/include/eosio/chain/abi_serializer.hpp:7,
                 from /eos/libraries/chain/abi_serializer.cpp:5:
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float32_t to_softfloat32(float)':
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float32_t*>(&f);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:296:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float64_t to_softfloat64(double)':
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float64_t*>(&d);
                                           ^
/eos/libraries/softfloat/source/include/softfloat.hpp:299:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'float from_softfloat32(float32_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:302:39: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<float*>(&f);
                                       ^
/eos/libraries/softfloat/source/include/softfloat.hpp: In function 'double from_softfloat64(float64_t)':
/eos/libraries/softfloat/source/include/softfloat.hpp:305:40: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *reinterpret_cast<double*>(&d);
                                        ^


c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libraries/chain/CMakeFiles/eosio_chain.dir/controller.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
```

**Comment by NorseGaud** [comment]
## Ubuntu 16.04
`-y -P -m`: Works
( apt-get install clang ) `-y`:

**Comment by NorseGaud** [comment]
## Centos 7
`-y -P -m`: Works
(yum install gcc-c++) `-y`:

**Comment by NorseGaud** [comment]
## Darwin

`-y -P -m`: Works
`-y`: Works

**Comment by heifner** [comment]
We will need some version of these fixes for `release/1.8.x` branch.

**Pull request closed without merging**
