### PR TITLE
Update instructions in README.md

### PR DESCRIPTION
**Pull request by ukarlsson**
I have tried to update the instructions to make it possible to get going with the master branch. I have added a link to the `README.md` for the `dawn-2.x` branch to keep these instructions separate in order to reduce confusion.

I have also tried to make the instructions a bit easier to follow also by not having the user change directories, clearing up the wording, and using more intuitive placeholder for the generated keys.

I have moved down instructions for manual building closer to the section for installing manual dependencies.

I look forward to improving these instructions further, but I think this would be a good start! :)

### CODE REVIEW

**Comment by ukarlsson** [comment]
@spoonincode please take a look! :)

**Comment by spoonincode** [comment]
Not ignoring you; it's just that a lot is still in rapid flux. For example there is a desire to have make install be included in the build script; and a new external dependency was thrusted in to master today.

**Comment by ukarlsson** [comment]
No worries thanks for the heads up!

**Comment by gleehokie** [comment]
@ukarlsson we modified this file greatly over the past few weeks including today (see PR #1905).  I think we picked up most of your changes, if you spot something that needs to be added still please submit a new PR.  Thank you!

**Pull request closed without merging**
