### PR TITLE
Fix build script for Amazon Linux 2

### PR DESCRIPTION
**Pull request by spoonincode**
A user implicitly reported via #5840 that Amazon Linux 2 does not build out of the box. Fix the build script to handle it.

```
$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

### CODE REVIEW

**Comment by wanderingbort** [comment]
I would prefer an actual review from someone who knows the build scripts but should this be backported on to 1.3.x as well for a patch release?

**Comment by spoonincode** [comment]
ah yeah should probably be targeted to 1.3. FWIW I did test building on both after the change

**Comment by heifner** [comment]
Automatic rebase via github didn't work. Need to manually rebase to release branch.

**Comment by spoonincode** [comment]
replacing with #5872 so that it hits 1.3.x first

**Pull request closed without merging**
