### PR TITLE
remove keep_processing in the for loop of kv_get_rows

### PR DESCRIPTION
**Pull request by linhuang-blockone**
## Change Description

The `keep_processing` in `kv_get_rows` is unnecessary and prevents rows being fetched. Remove it and bring it matched to develop branch. With the change, previously failed eosjs integration tests pass now.

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [X] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [X] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Review by bradlhart — APPROVED** [review]
Resolves the failed test with eosjs

**Comment by heifner** [comment]
This reverts the recent https://github.com/EOSIO/eos/pull/10146 @huangminghuang

**Review by huangminghuang — APPROVED** [review]

**Comment by heifner** [comment]
Why is this unnecessary?

**Review by huangminghuang — COMMENTED** [review]
I don't have problem to remove it; however, as I remembered, similar logic exists for the db tables. Do we also want to remove the time checking for the db?

**Review by heifner — CHANGES_REQUESTED** [review]
Why is this not needed?

**Comment by linhuang-blockone** [comment]
Thanks all for the comments. Talked to Huang-ming. There must be something else wrong. It must be a coincidence that Brad's test passed. Need to get to the root cause. Close this PR.

**Pull request closed without merging**
