### PR TITLE
BATS bash tests for build scripts + various other improvements and fixes

### PR DESCRIPTION
**Pull request by NorseGaud**
## Change Description
- BATS-CORE is being used for bash unit testing: This will allow us to ensure bash scripts function as they should for users. It's perfect for regression testing and consistency. (see tests/bash-bats/README.md)
- CICD Pipeline/steps run as the user cicd (instead of root)
  - Improvements to log output in buildkite showing a collapsed tab for each and every command the scripts run.
  - Auto retry failed step on -1 (Agent Lost)
- Users are prompted if 'which' is missing (we will install it for them if they want): https://github.com/EOSIO/eos/issues/7232
- All prompts are now properly wrapped to be user friendly: https://github.com/EOSIO/eos/issues/6931
- New eosio path: `~/eosio/$VersionFromCmakeFile/` to store dependencies and eosio: https://github.com/EOSIO/eos/issues/6931
- Script filename extensions are now .bash, indicating that bash is required to properly execute.
- Scripts now use #!/usr/bin/env to pull bash if it's installed into nonstandard /bin/ location
- Better uninstaller script, removing old "full_uninstaller" (readme updated)
- Build scripts support DRYRUN=true (doesn't execute anything, but shows you what it would do) and VERBOSE=true (shows the exact commands executed throughout script) for better troubleshooting.
- Scripts use `set -ieo pipefail` so they fail properly when a command fails and also show colors for users executing the script (colors not supported on mac yet).
- Using *_deps file for each distro
  - Package dependency files include flexibility by allowing us to specify what command is used to check if it exists or not (dpkg -s/rpm -qa)
  - no more extra space at end of deps file! (yay)
- Using helpers/functions for modularity, avoiding having to repeat ourselves in each eosio_build_* script
- Environment variables have been moved into a separate file for better flexibility
  - Test scripts can pull in the same variables
  - comments added for better comprehension 

### Compiler support
_You can see almost all of these tests passing in https://buildkite.com/EOSIO/eosio-base-images/builds/137

| OS | -P | existing compiler | existing c++/clang < required version | no existing compiler |
| --- | --- | --- | --- | --- |
| Darwin | :white_check_mark: | :white_check_mark: | :white_check_mark: Will prompt for pin/install clang8 | :heavy_check_mark: (Hasn't been tested) |
| Centos 7 | :white_check_mark: | :white_check_mark: devtoolset-7 | :heavy_check_mark: (Hasn't been tested) | :white_check_mark: Will prompt for install of build-essentials (fails: see below) |
| AmazonLinux 2 | :white_check_mark: | :white_check_mark:  gcc-c++  | :heavy_check_mark: (Hasn't been tested) | :white_check_mark: exits and notifies user  |
| Ubuntu 16.04 | :white_check_mark: | :heavy_check_mark: (Hasn't been tested) |  :white_check_mark: Will prompt for pin/install clang8 | :white_check_mark: exits and notifies user |
| Ubuntu 18.04 | :white_check_mark: | :heavy_check_mark: (Hasn't been tested) |  :white_check_mark: Will prompt for pin/install clang8 | :white_check_mark: Will prompt for install of build-essentials |

### List of issues
1. https://github.com/EOSIO/eos/issues/6931 : Prompts are now humane + install into version specific folder
2. https://github.com/EOSIO/eos/issues/7120 : Centos 7 will now use sudo for yum commands if $(whoami) = root
3. https://github.com/EOSIO/eos/issues/7262 : New directory structure should fix this
4. https://github.com/EOSIO/eos/issues/7260 : New logic should prevent this from being a problem
5. https://github.com/EOSIO/eos/issues/7232 : User prompts if missing which or c++ (and not using -P).

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by spoonincode** [comment]
I tried this on fresh 18.04 and it wouldn't use the system compiler is that intended?

**Comment by NorseGaud** [comment]
> I tried this on fresh 18.04 and it wouldn't use the system compiler is that intended?

Yep: The logic checks if c++/clang is version > 7. If it's < 7, it will install clang8

**Comment by spoonincode** [comment]
This was on a fresh 18.04 is that really how it is supposed to behave:

```
$  scripts/eosio_build.bash -m
scripts/eosio_build.bash: line 2: set: -i: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
Beginning build version: 3.0
EOSIO version to install: 1.9.0-develop
Thu May 16 17:33:27 UTC 2019
User: ubuntu
Current branch: bats-v3
You have chosen to include MongoDB support. Do you want for us to install MongoDB as well? (y/n)? n

 - Existing MongoDB will be used.
Architecture: Linux
=====================================================================================
======================= Starting EOSIO Dependency Install ===========================
OS name: Ubuntu
OS Version: 18.04
CPU cores: 16
Physical Memory: 16G
Disk space total: 608G
Disk space available: 406G
Do you wish to update APT-GET repositories? (y/n)? n
 - Proceeding without update!
Unable to find compiler "c++"! Pass in the -P option if you wish for us to install it OR set $CXX to the proper binary location. 
readlink: missing operand
Try 'readlink --help' for more information.
COMPILER_TYPE not set!
```

**Comment by NorseGaud** [comment]
> This was on a fresh 18.04 is that really how it is supposed to behave:
> 
> ```
> $  scripts/eosio_build.bash -m
> scripts/eosio_build.bash: line 2: set: -i: invalid option
> set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
> Beginning build version: 3.0
> EOSIO version to install: 1.9.0-develop
> Thu May 16 17:33:27 UTC 2019
> User: ubuntu
> Current branch: bats-v3
> You have chosen to include MongoDB support. Do you want for us to install MongoDB as well? (y/n)? n
> 
>  - Existing MongoDB will be used.
> Architecture: Linux
> =====================================================================================
> ======================= Starting EOSIO Dependency Install ===========================
> OS name: Ubuntu
> OS Version: 18.04
> CPU cores: 16
> Physical Memory: 16G
> Disk space total: 608G
> Disk space available: 406G
> Do you wish to update APT-GET repositories? (y/n)? n
>  - Proceeding without update!
> Unable to find compiler "c++"! Pass in the -P option if you wish for us to install it OR set $CXX to the proper binary location. 
> readlink: missing operand
> Try 'readlink --help' for more information.
> COMPILER_TYPE not set!
> ```

Fixed by removing set -i since Ubuntu defaults to /bin/dash and that doesn't have interactive mode ability like bash.

**Comment by NorseGaud** [comment]
Base image pipeline runs BATS and also runs the various builds with and without -P
https://buildkite.com/EOSIO/eosio-base-images/builds/61

All passing

**Comment by spoonincode** [comment]
This doesn't work on fresh 18.04 as non root user

```
ubuntu@bionic:~/eos$ scripts/eosio_build.bash 
Beginning build version: 3.0
EOSIO version to install: 1.9.0-develop
Tue May 21 18:12:35 UTC 2019
User: ubuntu
Current branch: bats-v3
=====================================================================================
======================= Starting EOSIO Dependency Install ===========================
Architecture: Linux
OS name: Ubuntu
OS Version: 18.04
CPU cores: 16
Physical Memory: 16G
Disk space total: 608G
Disk space available: 433G
[Ensuring installation of build-essential with C++7]
dpkg-query: package 'build-essential' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Do you wish to install it? (y/n)? y

./scripts/helpers/general.bash: line 20: /usr/bin/sudo -E: No such file or directory
Unable to find compiler: Pass in the -P option if you wish for us to install it or install a C++17 compiler and set $CXX and $CC to the proper binary locations. 
```

**Comment by NorseGaud** [comment]
Using BATS, I ran every situation I can think of (root user, cicd user, pinned, etc) here: https://buildkite.com/EOSIO/eosio-base-images/builds/90

**Comment by NorseGaud** [comment]
auto-buildkite-pipelines PR https://github.com/EOSIO/auto-buildkite-pipelines/pull/140

**Pull request merged**
