### PR TITLE
RocksDB temporary fix

### PR DESCRIPTION
**Pull request by larryk85**
## Change Description

Temporary fix to get the log jam unstuck until my bigger dependency changes come in.  This will install RocksDB with eos and add it to the tester configs.

## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Review by johndebord — APPROVED** [review]
LGTM

**Review by nksanthosh — APPROVED** [review]
This fixes the contracts unit test failures. Thank you!
---------
~/Work/eosio.contracts/build epe405_token_contract_error_msg !1 ?6 ················································································································· 09:02:28 AM
❯ make 
…
Warning, action <exec> does not have a ricardian contract
1 warning generated.
[100%] Linking CXX executable eosio.wrap.wasm
[100%] Built target eosio.wrap
[ 88%] No install step for 'contracts_project'
[ 94%] No test step for 'contracts_project'
[100%] Completed 'contracts_project'
[100%] Built target contracts_project
~/Work/eosio.contracts/build/tests epe405_token_contract_error_msg ?6 ·············································································································· 09:42:01 AM
❯ ./unit_test
Random number generator seeded to 1603978930
Running 106 test cases...
*** No errors detected

**Comment by allenhan2** [comment]
eos, cdt (develop), and contracts (develop) can be built. contracts test passed, cdt unit test passed, however, see integration test fails:
~/workspace/eosio/develop/eosio.cdt/build/tests/integration (develop) $ ./integration_tests
Random number generator seeded to 1603987151
Running 27 test cases...
3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: invalid variant index
    {"s":"invalid variant index"}
    thread-0  cf_system.cpp:14 eosio_assert
pending console output:
    {"console":""}
    thread-0  apply_context.cpp:143 exec_one
transaction_header: {"expiration":"2020-01-01T00:00:08","ref_block_num":6,"ref_block_prefix":571135864,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0}, billed_cpu_time_us: 2000
    {"header":{"expiration":"2020-01-01T00:00:08","ref_block_num":6,"ref_block_prefix":571135864,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0},"billed":2000}
    thread-0  tester.cpp:609 push_transaction

    {"code":"kvtest","acttype":"vriantupgrd","auths":[{"actor":"kvtest","permission":"active"}],"data":{},"expiration":6,"delay_sec":0}
    thread-0  tester.cpp:681 push_action
rethrow
    {}
    thread-0  kv_tests.cpp:152 test_method

/Users/yue.han/workspace/eosio/develop/eosio.cdt/tests/integration/main.cpp:17: fatal error: in "key_value_tests/variant_upgrade_tests": Caught Unexpected Exception

*** 1 failure is detected in the test module "Master Test Suite"
~/workspace/eosio/develop/eosio.cdt/build/tests/integration (develop) $

**Comment by larryk85** [comment]
> eos, cdt (develop), and contracts (develop) can be built. contracts test passed, cdt unit test passed, however, see integration test fails (it could be different issue):
> ~/workspace/eosio/develop/eosio.cdt/build/tests/integration (develop) $ ./integration_tests
> Random number generator seeded to 1603987151
> Running 27 test cases...
> 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
> assertion failure with message: invalid variant index
> {"s":"invalid variant index"}
> thread-0 cf_system.cpp:14 eosio_assert
> pending console output:
> {"console":""}
> thread-0 apply_context.cpp:143 exec_one
> transaction_header: {"expiration":"2020-01-01T00:00:08","ref_block_num":6,"ref_block_prefix":571135864,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0}, billed_cpu_time_us: 2000
> {"header":{"expiration":"2020-01-01T00:00:08","ref_block_num":6,"ref_block_prefix":571135864,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0},"billed":2000}
> thread-0 tester.cpp:609 push_transaction
> 
> ```
> {"code":"kvtest","acttype":"vriantupgrd","auths":[{"actor":"kvtest","permission":"active"}],"data":{},"expiration":6,"delay_sec":0}
> thread-0  tester.cpp:681 push_action
> ```
> 
> rethrow
> {}
> thread-0 kv_tests.cpp:152 test_method
> 
> /Users/yue.han/workspace/eosio/develop/eosio.cdt/tests/integration/main.cpp:17: fatal error: in "key_value_tests/variant_upgrade_tests": Caught Unexpected Exception
> 
> *** 1 failure is detected in the test module "Master Test Suite"
> ~/workspace/eosio/develop/eosio.cdt/build/tests/integration (develop) $

Did you pull absolute latest CDT and rebuild CDT before running the integration tests?  That test was explicitly addressed in a commit.

**Comment by allenhan2** [comment]
No, I did not pull the latest since was testing on other issue with CDT, after pull the latest, it passed

**Comment by larryk85** [comment]
> No, I did not pull the latest since was testing on other issue with CDT, after pull the latest, it passed

Phew, you had me worried there for a minute.

**Comment by allenhan2** [comment]
FYI, I tried to make a CDT DEBUG build, but failed. (EOS debug build is good). I did not look into in detail since behind my task schedule now.

**Pull request merged**
