### PR TITLE
Remove deprecated flags from commands

### PR DESCRIPTION
**Pull request by lucca65**
The default `docker-compose.yml` file is breaking due to those flags

### CODE REVIEW

**Comment by ericiles** [comment]
The http-alias flag is not deprecated, and is very much necessary for this to work.

**Comment by lucca65** [comment]
Not true:

```
λ espx Docker git master* → docker-compose -f docker-compose.yml.bkp up
Recreating nodeosd        ... done
Starting docker_builder_1 ... done
Recreating keosd          ... done
Attaching to docker_builder_1, docker_nodeosd_1, docker_keosd_1
nodeosd_1  |
nodeosd_1  |
keosd_1    | 2853959ms thread-0   main.cpp:52                   main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
keosd_1    | Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
keosd_1    | std::exception::what: unrecognised option '--http-alias=keosd:8900'
keosd_1    |
nodeosd_1  | 2851753ms thread-0   main.cpp:119                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
nodeosd_1  | Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
nodeosd_1  | std::exception::what: unrecognised option '--http-alias=nodeosd:8888'
nodeosd_1  |
docker_builder_1 exited with code 0
docker_nodeosd_1 exited with code 254
docker_keosd_1 exited with code 0
```

**Comment by lucca65** [comment]
just run the `docker-compose.yml` file from master.

**Comment by ericiles** [comment]
It would appear that you already have an ```eosio/eos:latest``` image on your machine that was compiled some time ago, and is indeed missing the --http-alias flags. Try running ```docker rmi eosio/eos:latest``` and then doing ```docker-compose up``` and it should recompile with the latest code, and function as expected.

**Comment by lucca65** [comment]
Great, that does make a lot of sense, thanks!

**Pull request closed without merging**
