### PR TITLE
Remove dead code from fork_database

### LINKED ISSUE #7100: Remove dead code from fork_database
Following two member functions of `fork_datatbase` are not used anymore since PR #6149 which remove `controller::push_confirmation`.

- `fork_database::add( const header_confirmation& c )`
- `fork_database::set_bft_irreversible( block_id_type id )`

Let's cleanup above dead code if there is no chance of using them in future.

### PR DESCRIPTION
**Pull request by hqueue**
## Change Description

Remove following dead code from fork_database

- `fork_database::add( const header_confirmation& c )`
- `fork_database::set_bft_irreversible( block_id_type id )`

Abve  two member functions of `fork_datatbase` are not used anymore since PR #6149 which removed `controller::push_confirmation`.

Closes #7100

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by heifner** [comment]
@arhag I assume you have already made these changes on your fork db refactor branch.

**Comment by arhag** [comment]
@heifner: Yes, this dead code and more was removed in PR #6624.

I'm closing this PR since these changes will be incorporated into `develop` when the `forced-replay` branch is merged into `develop`.

**Comment by heifner** [comment]
Thanks @hqueue for your contribution.

**Comment by hqueue** [comment]
@heifner Got it. Thanks for the information and please also close issue #7100 if it is duped too :)

**Pull request closed without merging**
