### PR TITLE
Fixed required dependencies display on mac

### PR DESCRIPTION
**Pull request by swoopyy**
**Previously:**
The following dependencies are required to install EOSIO.
	1. automake\n\t2. Libtool\n\t3. llvm\n\t4. wget\n\t5. CMake\n\t6. GMP\n\t7. gettext\n\t8. MongoDB\n\t9. Doxygen\n\t10. Graphviz\n\t11. LCOV\n\t

**Now:**
The following dependencies are required to install EOSIO.
	1. automake
	2. Libtool
	3. llvm
	4. wget
	5. CMake
	6. GMP
	7. gettext
	8. MongoDB
	9. Doxygen
	10. Graphviz
	11. LCOV

### CODE REVIEW

**Comment by jgiszczak** [comment]
Pull requests must be issued against `EOSIO:develop`.  Hopefully buildkite will succeed when you resubmit.  That looks like a spurious failure to me.

**Comment by swoopyy** [comment]
#4946

**Comment by swoopyy** [comment]
#4946

**Comment by heifner** [comment]
Already merged into develop branch. Thank you.

**Pull request closed without merging**
