### PR TITLE
Fix docker cmake WASM_LLVM_CONFIG value

### PR DESCRIPTION
**Pull request by peterwillcn**
1. Fix cmake WASM_LLVM_CONFIG value

### CODE REVIEW

**Comment by toonsevrin** [comment]
@peterwillcn I merged this with my own pr, can you close this in favor of #292?

**Comment by jgiszczak** [comment]
Technically a cosmetic update.  The new caching of WASM_LLVM_CONFIG was carefully designed to be backwards compatible, supporting either syntax.  That said, I'm all in favor of regularizing the usage.

**Comment by toonsevrin** [comment]
@bytemaster Just close this pr,  #292 implemented this.

**Comment by peterwillcn** [comment]
@bytemaster  Close this use new PR https://github.com/EOSIO/eos/pull/308

**Pull request closed without merging**
