### PR TITLE
mv test updated v1.7.0 dropped in favor of newer

### PR DESCRIPTION
**Pull request by dimas1185**
## Change Description

v1.7.0 was dropped from buildkite so mv test was updated to use newer version.
This also required to slightly change multiversion test because of it was based on fact that v1.7.0 was not able to use PREACTIVATE_FEATURE. This decision was discussed with Kevin and Areg.

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [x] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by heifner** [comment]
Doesn't look like the multi-version test was run.

**Comment by kj4ezj** [comment]
The multiversion test can be run on this pull request by setting this in your build environment:
```bash
SKIP_MULTIVERSION_TEST='false'
```
This flag is documented [here](https://github.com/EOSIO/eos/tree/318276f513165c4c51d8443bb4717183e32a36dd/.cicd#variables) and [here](https://buildkite.com/EOSIO/eosio/builds/30709#annotation-documentation), and was communicated on IM [here](https://blockone.slack.com/archives/CMTAZ9L4D/p1633557636095400?thread_ts=1633534852.082400&cid=CMTAZ9L4D).

**Comment by kj4ezj** [comment]
We should not rely upon Buildkite or GitHub for any of our test assets. To this end, as part of story [AUTO-1466](https://blockone.atlassian.net/browse/AUTO-1466), Automation stood up the [eosio-test-artifacts](https://s3.console.aws.amazon.com/s3/object/eosio-test-artifacts?region=us-west-2) S3 bucket and put the `v1.7.0` Ubuntu 18.04 release binary at:
```
https://eosio-test-artifacts.s3.us-west-2.amazonaws.com/eos/multiversion-test/686f0de-eosio_1.7.0-1-ubuntu-18.04_amd64.deb
```
Better yet, this bucket is `public-read` so the EOSIO community can actually run our tests. If you guys decide to consume a different test fixture, please either put it in this bucket or let Automation know and we will put it in that bucket.

**Comment by dimas1185** [comment]
@heifner here is succesful build with multiversion enabled from this branch.
https://buildkite.com/EOSIO/eosio/builds/30959#_
Also, I noticed that earlier versions before 2.1.x don't work due to some fork db exceptions and I'm planning to make a jira for that. But release/2.1.x works just fine.
@kj4ezj this will be the other change. Anyway test versus 1.7.0 seems to be unneeded and to run multiversion test for later versions we need to slightly change it.

**Review by heifner — APPROVED** [review]

**Pull request merged**
