### PR TITLE
Fix eosio.token

### PR DESCRIPTION
**Pull request by elmato**
* Enforce max-supply
* Enforce same symbol (symbole_code+precision) when transfer/issuing
* Fix ABI
* Allow precision greater than 15 decimals
* Add tests

#2291

### CODE REVIEW

**Comment by Akagi201** [comment]
Hope this pr be merged asap.
I want to test it.

**Comment by Akagi201** [comment]
root@b8cac977051a:~# cleos push action eosio.token issue '[ "user", "100.0000 EOS", "memo" ]' -p eosio
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
condition: assertion failed: unable to find key

I tested this PR. And got errors above. @elmato

**Comment by elmato** [comment]
@Akagi201 can you post the create command you are using?

**Comment by Akagi201** [comment]
@elmato cleos push action eosio.token create '[ "eosio", "1000000000.0000 EOS", 0, 0, 0]' -p eosio.token

**Comment by elmato** [comment]
@Akagi201 
Check that the token is created before executing the **issue** action.

**Comment by Akagi201** [comment]
@elmato Sure, I already created the token.

I may check it twice.

**Pull request merged**
