### PR TITLE
Read only mode

### PR DESCRIPTION
**Pull request by heifner**
- Create a new read-only db mode where incoming blocks are processed but with no speculative processing of blocks. This is similar to head mode except for no speculative execution or relaying of transactions are performed.
- In read-only mode no p2p connections are allowed since transactions are not speculatively executed or relayed.
- This mode is useful for plugins such as the mongo_db_plugin where consistent state is the most important characteristic.
- Note that non-irreversible blocks are still processed so forks are recorded when they happen.

### CODE REVIEW

**Comment by abourget** [comment]
> In read-only mode no p2p connections are allowed since transactions are not speculatively executed or relayed.

Curious.. how can _incoming blocks_ be applied if no p2p connections are allowed?

**Comment by abourget** [comment]
Do you mean we refuse incoming connections, but outgoing are okay?

**Comment by heifner** [comment]
@abourget Correct incoming connections are not allowed since transactions would be dropped on the floor and not speculatively executed.

**Comment by ScottSallinen** [comment]
This is /almost/ perfect for a use case I have in mind: block-only relays, to speed up block propagation. I imagine them being run alongside other seed nodes, so producers have routes for TX's, but also a fast route for blocks.

With this in mind, would it be possible to optionally enable accepting incoming connections? This way, a block relay could be made public for other producer's own block relays to connect to.

**Pull request merged**
