### PR TITLE
Updated Readme & Generated Doxygen

### PR DESCRIPTION
**Pull request by bytemaster**

### CODE REVIEW

**Comment by brianjohnson5972** [comment]
@bytemaster Did you mean to commit the change in ProcessedGeneratedTransaction to make output be a vector of optional<MessageOutput>?  I know you are busy with a ton of stuff on documentation and release, so wanted to ping you on it, but just ignore me if you already know about it.  Or let me know if you need me to do something for it.

**Comment by bytemaster** [comment]
I did not mean to do that...  yikes..

**Comment by brianjohnson5972** [comment]
I can push it right now if you want me to

**Comment by brianjohnson5972** [comment]
Made a pull request, I'll close it if you take care of it another way.

**Pull request merged**
