### PR TITLE
Add support for 160-bit keys and key encoder type  

### PR DESCRIPTION
**Pull request by venediktov**
Hi @heifner ,
I have added support for 160-bit keys aka `ripemd160` on the command line --key-type ripemd160
I have also added --encode-type [hex/dec] for some cases like --key-type i256 --encode-type hex

I have tested on my smart contract it works in our project now 

utils.hpp
```
static key160 checksum160_to_key160(const checksum160& value) {
        key160 k;
        const uint32_t  *p32 = reinterpret_cast<const uint32_t *>(&value);
        k.data()[0] = p32[0];
        k.data()[1] = p32[1];
        k.data()[2] = p32[2];
        k.data()[3] = p32[3];
        k.data()[4] = p32[4];
        return k;
    } 
 ``` 

contract.cpp
```
    ///@abi table tokenholders i64
    struct token_holder
    {
        account_name account{};
        checksum160 address{};
        uint64_t balance{};

        account_name primary_key() const { return account; }
        key160 by_address() const { return checksum160_to_key160(address); }

        EOSLIB_SERIALIZE(token_holder, (account)(address)(balance))
    };
```

Please let me know if anything you want to change / add

Thank you!

### CODE REVIEW

**Comment by arhag** [comment]
@venediktov:

I didn't actually try testing this out, but I believe something like the following should work:
```
struct tokenholders {
   account_name  account;
   checksum160   address;
   int64_t       balance;

   uint64_t primary_key() const { return account; }

   eosio::key256 by_ripemd_hash()const {
      return eosio::key256::make_from_word_sequence<uint8_t>( address[0], address[1], address[2], address[3], 
                                                              address[4], address[5], address[6], address[7],
                                                              address[8], address[9], address[10], address[11],
                                                              address[12], address[13], address[14], address[15],
                                                              address[16], address[17], address[18], address[19] );
      // For developer convenience (while still avoiding unnecessary copies), maybe create an overload of fixed_key constructor which takes a regular C arrays rather than only a std::array?
   }

   EOSLIB_SERIALIZE( tokenholders, (account)(address)(balance) )
};

typedef eosio::multi_index< N(tokenholders), tokenholders,
                            eosio::indexed_by< N(byaddress), eosio::const_mem_fun<tokenholders, eosio::key256, &certrow::by_ripemd_hash> >
                          > tokenholders_table;
```

Since the least significant 12 bytes of key256 will all be 0s, that means the hex string you use as the lookup key will need 24 '0's at the end. Of course, if you keep your `ripemd160` key type in chain_plugin, then it can do that automatically for the caller.

**Comment by venediktov** [comment]
```
/*
    static key160 checksum160_to_key160(const checksum160& value) {
        key160 k;
        const uint32_t  *p32 = reinterpret_cast<const uint32_t *>(&value);
        k.data()[0] = p32[0];
        k.data()[1] = p32[1];
        k.data()[2] = p32[2];
        k.data()[3] = p32[3];
        k.data()[4] = p32[4];
        return k;
    }
*/
    static key256 checksum160_to_key256(const checksum160& value) {

      return eosio::key256::make_from_word_sequence<uint8_t>( value.hash[0],  value.hash[1],  value.hash[2], value.hash[3],
                                                              value.hash[4],  value.hash[5],  value.hash[6], value.hash[7],
                                                              value.hash[8],  value.hash[9],  value.hash[10], value.hash[11],
                                                              value.hash[12], value.hash[13], value.hash[14], value.hash[15],
                                                              value.hash[16], value.hash[17], value.hash[18], value.hash[19]);
    }
```

@arhag , packing to the front and using `--key-type ripemd160`  works , so I will revert changes related to webassembly /chain , basically leave only chain_plugin and main.cpp .
Thank you!

**Comment by venediktov** [comment]
@arhag and @heifner , it only worked before I reverted the changes , chain::key160_t is no longer available and I believe chain::key256_t will read 256 bits from the tables but table only stores 160 bits.
IMHO the only way to make it work with existing chain::key256_t is to make it read 160 bits only for comparison ?
Current ripemd160 code in the chain_plugin.hpp I am testing with your @arhag suggested change on the contract side is below and it does not work.

```
template<>
 struct keytype_converter<chain_apis::ripemd160, chain_apis::hex> {
     using input_type = chain::checksum160_type;
     using index_type = chain::index256_index;
     static auto function() {
        return [](const input_type& v) {
            //key160 support with padding zeros in the end of key256
            chain::key256_t k;
            uint8_t* p8 = (uint8_t*)v._hash;
            auto fixed_k = eosio::key256::make_from_word_sequence<uint8_t>(
                    p8[0],  p8[1], p8[2], p8[3], p8[4],  p8[5], p8[6], p8[7], p8[8],  p8[9],
                    p8[10], p8[11], p8[12], p8[13], p8[14],p8[15], p8[16], p8[17], p8[18], p8[19]
            );
            k[0] = fixed_k.data()[0];
            k[1] = fixed_k.data()[1];
            return k;
        };
     }
 };
```

The above will not work with your proposed solution in the contract 
```
static key256 checksum160_to_key256(const checksum160& value) {

      return eosio::key256::make_from_word_sequence<uint8_t>( value.hash[0],  value.hash[1],  value.hash[2], value.hash[3],
                                                              value.hash[4],  value.hash[5],  value.hash[6], value.hash[7],
                                                              value.hash[8],  value.hash[9],  value.hash[10], value.hash[11],
                                                              value.hash[12], value.hash[13], value.hash[14], value.hash[15],
                                                              value.hash[16], value.hash[17], value.hash[18], value.hash[19]);
    }
```


But this below will.
```
template<>
  struct keytype_converter<chain_apis::ripemd160, chain_apis::hex> {
      using input_type = chain::checksum160_type;
      using index_type = chain::index160_index;
      static auto function() {
         return [](const input_type& v) {
             chain::key160_t k;
             k[0] = ((uint32_t *)&v._hash)[0];
             k[1] = ((uint32_t *)&v._hash)[1];
             k[2] = ((uint32_t *)&v._hash)[2];
             k[3] = ((uint32_t *)&v._hash)[3];
             k[4] = ((uint32_t *)&v._hash)[4];
             return k;
         };
      }
```

This implementation works with your `key256` solution in smart contract as it only reads 160 bits .
So having only chain::key160_t without touching contract library will work , however I think it seems more practical to have fixes on both sides ?

Also and I can be wrong , but off the top of my head I don't think the index used in the smart contract is what gets read by index in the chain , it looks like as it reads storage directly and the storage only has 160 bits ?

Please advise. I am ok with holding off the changes until you decide what to do with them.
Thank you!

**Comment by venediktov** [comment]
@arhag , the new code is not checked into the branch tracking this pull request
```
template<>
 struct keytype_converter<chain_apis::ripemd160, chain_apis::hex> {
     using input_type = chain::checksum160_type;
     using index_type = chain::index256_index;
     static auto function() {
        return [](const input_type& v) {
            //key160 support with padding zeros in the end of key256
            chain::key256_t k;
            uint8_t* p8 = (uint8_t*)v._hash;
            auto fixed_k = eosio::key256::make_from_word_sequence<uint8_t>(
                    p8[0],  p8[1], p8[2], p8[3], p8[4],  p8[5], p8[6], p8[7], p8[8],  p8[9],
                    p8[10], p8[11], p8[12], p8[13], p8[14],p8[15], p8[16], p8[17], p8[18], p8[19]
            );
            k[0] = fixed_k.data()[0];
            k[1] = fixed_k.data()[1];
            return k;
        };
     }
 };
```
I can check it in , but it does not work.

**Comment by venediktov** [comment]
@arhag and  @heifner , the only solution I found working with 160bit keys utilizing existing chain::key256_t ( chain_plugin ) and eosio::key256 ( on the contract size ) was zero padding by this style

```
template<>
 struct keytype_converter<chain_apis::ripemd160, chain_apis::hex> {
     using input_type = chain::checksum160_type;
     using index_type = chain::index256_index;
     static auto function() {
        return [](const input_type& v) {
            chain::key256_t k;
            memset(k.data(), 0, sizeof(k));
            memcpy(k.data(), v._hash, sizeof(v._hash));
            return k;
        };
     }
 }; 
```

Doing it with `fixed_key<32>` functions like `eosio::key256::make_from_word_sequence<T>` always produced incorrect padding in case when target was larger then source

**original 160bit** 
cc60a3aabc7dbac7bc2c8b39e646366fa6677116

after eosio::key256::make_from_word_sequence<T>

**cc60a3aabc7dbac7bc2c8b39e646366f**000000000000000000000000**a6677116**

expected 
**cc60a3aabc7dbac7bc2c8b39e646366fa6677116**000000000000000000000000

Please let me know if this code ok with you or you require more changes. 
As a side note `sha256` does not need to change it does not exhibit padding issues, so I left it untouched.
Thank you!

**Pull request merged**
