### PR TITLE
increasing vote cap from 30 to 999

### PR DESCRIPTION
**Pull request by kesar**
Related https://medium.com/@eoscafeblock/should-block-one-vote-a-case-for-increasing-vote-cap-from-30-to-unlimited-f7583f926ff7

### CODE REVIEW

**Comment by wanderingbort** [comment]
These copies of the system contract are painfully out of date and this has not been the source of those contracts for months.

Please resubmit to https://github.com/EOSIO/eosio.contracts

**Comment by wanderingbort** [comment]
Also, we use `master` is for released tags.  This is likely a better targetted to the `develop` branch in the appropriate repo

**Comment by kesar** [comment]
we could delete them to avoid mistakes like mine

**Comment by wanderingbort** [comment]
@kesar We plan on deleting them as we migrate our smoke/integration tests away from them 😇

**Pull request closed without merging**
