### PR TITLE
enable mongo_db_plugin in config.ini by default

### PR DESCRIPTION
**Pull request by noprom**
Currently we can enable the mongo_db_plugin in config.ini for docker images.

### CODE REVIEW

**Comment by kesar** [comment]
is it working with the new dawn4.0 version mongo plugin?

**Comment by noprom** [comment]
@kesar  I've tested it in dawn3.0 and it works fine.
Will test it in dawn4.0 soon.

**Comment by heifner** [comment]
This is OBE as the mongodb plugin has not been updated for Dawn 4.x.

**Comment by noprom** [comment]
@heifner, will that be supported in EOS1.0 when release?

**Comment by heifner** [comment]
No

**Comment by noprom** [comment]
Hi @heifner , will `mongo_db_plugin` be supported in the future? Or you just don't have any plans on develop this plugin anymore?

**Pull request closed without merging**
