### PR TITLE
Fix openssl elliptic compile issue

### PR DESCRIPTION
**Pull request by harrywong**

### CODE REVIEW

**Comment by harrywong** [comment]
May be we also need to provide a test for openssl-elliptic and mixed-elliptic build.

**Comment by spoonincode** [comment]
Can you provide a little more description on what this fixes? The expectation is that this file will not be used in our compilation due to secp256k1 library usage.

**Comment by harrywong** [comment]
Yes, but the fc library also provide the option(aka. `ECC_IMPL` option) to be built with OpenSSL.
This fixes the compile issue when building fc library with OpenSSL-ECC implementation.

**Comment by bytemaster** [comment]
It only fixes the compile issue, it doesn't actually make it canonical.  We should make sure the implementations are the same.

**Comment by harrywong** [comment]
Hi @bytemaster, I've implemented canonical semantic, thx.

**Pull request closed without merging**
