### PR TITLE
provide some basic issue info, to avoid too much questions

### PR DESCRIPTION
**Pull request by lazaridiscom**

### CODE REVIEW

**Comment by heifner** [comment]
This information is in the readme.

**Comment by lazaridiscom** [comment]
@heifner , wrong branch, should go to default branch (master).

**Comment by heifner** [comment]
@lazaridiscom comment still stands. This info is in the readme.

**Comment by lazaridiscom** [comment]
@heifner, this is not about an additional document, but about the Issue-Template (which is more or less standard-procedure on github), see the clarifying issue #5295.

Apologies for not clarifying this immediately.

**Comment by lazaridiscom** [comment]
superseded by #5321

**Pull request closed without merging**
