### PR TITLE
EOSIO build dynamic CMAKE_BUILD_TYPE. Address issue #1949

### PR DESCRIPTION
**Pull request by pacificcode**
Added dynamic CMAKE_BUILD_TYPE, default build type CMAKE_BUILD_TYPE=Release. Set env var EOS_BUILD_TYPE=[Debug|Release|RelWithDebInfo|MinSizeRel] to enable.
This PR addressed issue #1949.

### CODE REVIEW

**Comment by spoonincode** [comment]
Just a heads up that Release is -O3 and RelWithDebInfo is -O2. I'm not saying that's a problem, just pointing it out.

**Comment by pacificcode** [comment]
@spoonincode, would it be best to default to RelWithDebInfo?

**Comment by spoonincode** [comment]
I don't think so, just pointing it out since I don't think most are aware of the difference

**Comment by pacificcode** [comment]
Great, then this PR is ready to go when you have a sec to merge.

**Pull request merged**
