### PR TITLE
Fix for 2416 : discriminating prefixes 

### PR DESCRIPTION
**Pull request by wanderingbort**
resolve ambiguous prefixes on pub/priv keys and sigs

The prefix is now `PUB/PVT/SIG.K1/R1.`

The legacy rules are still in place so, a public key prefixed with `EOS` is still treated as an typeless-checksummed `PUB.K1.`  and a wif private key is imported as a `PVT.K1.`

fixes EOSIO/eos#2416

### CODE REVIEW

**Comment by wanderingbort** [comment]
triple click seems to work 😈

**Comment by spoonincode** [comment]
But that's only because triple click is whole line. I mean hey let's try, can you import my key PVT.R1.yXiskXjsTkQ5GxhQp1jJqPLfz2cZkah71ZZVwsAciAxsMbiDU in to your wallet?

**Comment by heifner** [comment]
`_` works if you want to use that instead of `.`

Let's try underscore:, can you import my key PVT_R1_yXiskXjsTkQ5GxhQp1jJqPLfz2cZkah71ZZVwsAciAxsMbiDU in to your wallet?

**Comment by danirabbani90** [comment]
Hi there , i have the question is that can i be able to customise the Prefix address symbol rather than EOS ?

**Pull request merged**
